config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  scope "(:locale)", locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users
    resources :users, only: %i[show edit update] # Add other actions if needed

    post "flush_and_reseed", to: "static#flush_and_reseed"
    # resources :contacts, only: [:new, :create]

    resources :contacts, only: %i[new create]

    # Video
    get "videos/back", to: "videos#go_back", as: "step_back"
    get "videos/go_to_select_chapters", to: "videos#go_to_select_chapters", as: "go_to_select_chapters"

    get "videos/start", to: "videos#start", as: "start"
    post "videos/start", to: "videos#start_post", as: "start_post"

    get "videos/occasion", to: "videos#occasion", as: "occasion"
    post "videos/occasion", to: "videos#occasion_post", as: "occasion_post"

    # get 'videos/destinataire', to: "videos#destinataire", as: "destinataire"
    # post 'videos/destinataire', to: "videos#destinataire_post", as: "destinataire_post"

    get "videos/info_destinataire", to: "videos#info_destinataire", as: "info_destinataire"
    post "videos/info_destinataire", to: "videos#info_destinataire_post", as: "info_destinataire_post"

    get "videos/destinataire_details", to: "videos#destinataire_details", as: "destinataire_details"
    post "videos/destinataire_details_post", to: "videos#destinataire_details_post", as: "destinataire_details_post"
    delete "videos/delete_destinataire/:id", to: "videos#delete_destinataire", as: "delete_destinataire"
    patch "videos/update_destinataire/:id", to: "videos#update_destinataire", as: "update_destinataire"

    get "videos/date_fin", to: "videos#date_fin", as: "date_fin"
    post "videos/date_fin", to: "videos#date_fin_post", as: "date_fin_post"

    get "videos/introduction", to: "videos#introduction", as: "introduction"
    post "videos/introduction", to: "videos#introduction_post", as: "introduction_post"

    get "videos/photo_intro", to: "videos#photo_intro", as: "photo_intro"
    post "videos/photo_intro", to: "videos#photo_intro_post", as: "photo_intro_post"
    delete "videos/drop_preview/:id", to: "videos#drop_preview", as: "drop_preview"

    get "videos/select_chapters", to: "videos#select_chapters", as: "select_chapters"
    post "videos/select_chapters", to: "videos#select_chapters_post", as: "select_chapters_post"

    get "videos/music", to: "videos#music", as: "music"
    post "videos/music", to: "videos#music_post", as: "music_post"
    patch "videos/update_video_music_type", to: "videos#update_video_music_type", as: "update_video_music_type"
    delete "videos/drop_custom_music/:id", to: "videos#drop_custom_music", as: "drop_custom_music"

    get "videos/dedicace", to: "videos#dedicace", as: "dedicace"
    post "videos/dedicace", to: "videos#dedicace_post", as: "dedicace_post"

    get "videos/share", to: "videos#share", as: "share"
    post "videos/share", to: "videos#share_post", as: "share_post"
    get "videos/skip_share", to: "videos#skip_share", as: "skip_share"

    get "videos/content", to: "videos#content", as: "content"
    post "videos/content", to: "videos#content_post", as: "content_post"
    get "videos/skip_content", to: "videos#skip_content", as: "skip_content"

    get "videos/content_dedicace", to: "videos#content_dedicace", as: "content_dedicace"
    get "videos/:id/stream", to: "videos#stream_video", as: "stream_video"
    post "videos/content_dedicace", to: "videos#content_dedicace_post", as: "content_dedicace_post"
    get "videos/skip_content_dedicace", to: "videos#skip_content_dedicace", as: "skip_content_dedicace"

    get "videos/deadline", to: "videos#deadline", as: "deadline"
    post "videos/deadline", to: "videos#deadline_post", as: "deadline_post"
    get "videos/skip_deadline", to: "videos#skip_deadline", as: "skip_deadline"

    get "videos/dedicace_de_fin", to: "videos#dedicace_de_fin", as: "dedicace_de_fin"
    patch "/:id/videos/dedicace_de_fin_post", to: "videos#dedicace_de_fin_post", as: "dedicace_de_fin_post"
    get "videos/skip_dedicace_de_fin", to: "videos#skip_dedicace_de_fin", as: "skip_dedicace_de_fin"

    get "videos/confirmation", to: "videos#confirmation", as: "confirmation"
    post "videos/confirmation", to: "videos#confirmation_post", as: "confirmation_post"
    get "videos/skip_confirmation", to: "videos#skip_confirmation", as: "skip_confirmation"

    patch "videos/:id/update_video_slot", to: "videos#update_video_slot", as: "update_video_slot"

    get "videos/:id/get_video_slot_status", to: "videos#get_video_slot_status", as: "get_video_slot_status"

    get "videos/edit_video", to: "videos#edit_video", as: "edit_video"
    post "videos/edit_video_post", to: "videos#edit_video_post", as: "edit_video_post"
    get "videos/skip_edit_video", to: "videos#skip_edit_video", as: "skip_edit_video"
    delete "videos/delete_video_chapter/:id", to: "videos#delete_video_chapter", as: "delete_video_chapter"
    delete "videos/purge_chapter_attachment/:id", to: "videos#purge_chapter_attachment", as: "purge_chapter_attachment"

    get "videos/payment", to: "videos#payment", as: "payment"
    post "videos/payment_post", to: "videos#payment_post", as: "payment_post"

    get "videos/render_final_page", to: "videos#render_final_page", as: "render_final_page"

    get "join/videos/:id", to: "videos#join", as: "join"

    get "projects/as_creator", to: "projects#as_creator_projects", as: "as_creator_projects"
    get "projects/as_collaborator", to: "projects#as_collaborator_projects", as: "as_collaborator_projects"
    get "projects/participants_progress", to: "projects#participants_progress", as: "participants_progress"
    get "projects/collaborator_video_details/:id", to: "projects#collaborator_video_details",
                                                   as: "collaborator_video_details"

    get "projects/collaborator_manage_chapters/:id", to: "projects#collaborator_manage_chapters",
                                                     as: "collaborator_manage_chapters"
    get "projects/collaborator_manage_dedicace/:id", to: "projects#collaborator_manage_dedicace",
                                                     as: "collaborator_manage_dedicace"
    post "projects/collaborator_chapters_post", to: "projects#collaborator_chapters_post",
                                                as: "collaborator_chapters_post"
    post "projects/edit_collaborator_chapters_post", to: "projects#edit_collaborator_chapters_post",
                                                     as: "edit_collaborator_chapters_post"
    delete "projects/delete_collaborator_chapter/:id", to: "projects#delete_collaborator_chapter",
                                                       as: "delete_collaborator_chapter"
    post "projects/collaborator_dedicace_de_fin_post", to: "projects#collaborator_dedicace_de_fin_post",
                                                       as: "collaborator_dedicace_de_fin_post"

    get "projects/creator_manage_chapters/:id", to: "projects#creator_manage_chapters", as: "creator_manage_chapters"
    get "projects/creator_manage_dedicace/:id", to: "projects#creator_manage_dedicace", as: "creator_manage_dedicace"
    post "projects/creator_chapters_post", to: "projects#creator_chapters_post", as: "creator_chapters_post"
    post "projects/edit_creator_chapters_post", to: "projects#edit_creator_chapters_post",
                                                as: "edit_creator_chapters_post"
    delete "projects/delete_creator_chapter/:id", to: "projects#delete_creator_chapter", as: "delete_creator_chapter"
    post "projects/creator_dedicace_de_fin_post", to: "projects#creator_dedicace_de_fin_post",
                                                  as: "creator_dedicace_de_fin_post"
    post "projects/creator_refresh_video", to: "projects#creator_refresh_video", as: "creator_refresh_video"
    post "projects/approving_collaborator_attachments", to: "projects#approving_collaborator_attachments",
                                                        as: "approving_collaborator_attachments"
    get "projects/invite_collaborators", to: "projects#invite_collaborators", as: "invite_collaborators"
    post "projects/invite_collaborators_post", to: "projects#invite_collaborators_post", as: "invite_collaborators_post"

    delete "projects/delete_collaboration/:id", to: "projects#delete_collaboration", as: "delete_collaboration"
    patch "projects/:id/modify_deadline", to: "projects#modify_deadline", as: "modify_deadline"
    patch "projects/:id/close_project", to: "projects#close_project", as: "close_project"

    get "videos/:id/concat_status", to: "videos#concat_status", as: "video_concat_status"

    # Static pages
    get "about", to: "static#about", as: "about"
    get "pricing", to: "static#pricing", as: "pricing"

    # Users profile pages
    get "profile", to: "users#show", as: :profile

    # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
    # Can be used by load balancers and uptime monitors to verify that the app is live.
    get "up" => "rails/health#show", as: :rails_health_check

    # Defines the root path route ("/")
    root "static#home"
  end
end

app/models/video.rb
class Video < ApplicationRecord
  enum :video_type, { solo: 0, colab: 1 }
  enum :occasion, { anniversaire: 0, mariage: 1 }
  enum :theme, { specific_request: 0, theme_1: 1, theme_2: 2 }
  enum :introduction_video, {notre_star_ce_soir: 0}
  enum :music_type, { whole_video: 0, by_chapters: 1 }
  enum concat_status: { pending: 0, processing: 1, completed: 2, failed: 3 }
  enum project_status: { started: 0, in_progress: 1, finished: 2, closed: 3 }

  has_many :video_destinataires, dependent: :destroy
  has_many :video_chapters, dependent: :destroy
  has_many :dedicace_contents, dependent: :destroy
  has_many :collaborations, dependent: :destroy
  has_many :collaborator_dedicaces, dependent: :destroy
  has_many :collaborator_chapters, dependent: :destroy
  has_one :video_dedicace, dependent: :destroy

  # has_many :video_musics, dependent: :destroy
  # has_many :musics, through: :video_musics

  has_many :video_previews, dependent: :destroy
  has_many :previews, through: :video_previews
  has_many :collaborations, dependent: :destroy

  has_one_attached :final_video
  has_one_attached :final_video_with_watermark
  has_one_attached :final_video_with_transition
  has_one_attached :final_video_xml

  belongs_to :user
  belongs_to :music, optional: true
  belongs_to :dedicace, optional: true

  SOLO_WAY = %w[start occasion info_destinataire destinataire_details date_fin introduction
                photo_intro select_chapters music dedicace share content deadline edit_video content_dedicace payment]
  COLAB_WAY = %w[start occasion info_destinataire destinataire_details date_fin introduction
                 photo_intro select_chapters music dedicace share content dedicace_de_fin confirmation deadline edit_video content_dedicace payment]

  def video_destinataire
    video_destinataires.last
  end

  def final_video_duration
    if final_video.attached? && final_video.blob.present?
      analyzer = ActiveStorage::Analyzer::VideoAnalyzer.new(final_video.blob)
      metadata = analyzer.metadata
      metadata[:duration] if metadata
    else
      nil
    end
  end

  def get_preview
    return unless video.previewable? # => true

    img_preview = video.preview(resize: "800x1400").processed # Returns an active storage instance with the file type mp4 instead of the expected png thumbnail
    img_preview.service_url # Fails with exception (see next snippet)
  end

  def generate_token
    self.token = SecureRandom.urlsafe_base64(20)
    generate_token if Video.exists?(token:)
  end

  def validate_start
    Video.video_types.keys.include?(video_type.downcase) && way.include?(stop_at)
  end

  def validate_occasion
    Video.occasions.keys.include?(occasion.downcase) && way.include?(stop_at)
  end

  def validate_destinataire(video_destinataire)
    VideoDestinataire.genres.keys.include?(video_destinataire.genre) && way.include?(stop_at)
  end

  def validate_info_destinataire(video_destinataire)
    return false if video_destinataire.name.empty?
    return false if video_destinataire.age.nil? || !video_destinataire.age.is_a?(Numeric)
    # return false if video_destinataire.more_info.empty?
    return false if video_destinataire.passions_and_hobbies.empty?
    return false if video_destinataire.personality_description.empty?
    return false if video_destinataire.favorite_quotes.empty?
    return false unless way.include?(stop_at)

    true
  end

  def validate_date_fin
    return false if end_date.nil? || !end_date.is_a?(ActiveSupport::TimeWithZone)
    return false unless way.include?(stop_at)

    true
  end

  def validate_introduction
    return false unless Video.introduction_videos.include?(introduction_video.downcase)
    return false if specific_request? && theme_specific_request.blank?
    return false unless way.include?(stop_at)

    true
  end

  def validate_photo_intro
    return false if previews.count > 3 || previews.count == 0

    true
  end

  def next_step
    curr_step = way.find_index stop_at
    return 0 if curr_step.nil?
    return way.size if finish?

    way[curr_step + 1]
  end

  def finish?
    current_step == way.last
  end

  def current_step
    curr_step = way.find_index stop_at
    return way[0] if curr_step.nil?

    way[curr_step]
  end

  def previous_step
    curr_step = way.find_index stop_at
    return way[0] if curr_step.nil? || curr_step <= 0

    way[curr_step - 1]
  end

  def way
    return SOLO_WAY if video_type == "solo"

    COLAB_WAY
  end

  def self.calculate_duration(duration_in_seconds)
    (duration_in_seconds.to_f / 60).ceil
  end

  def self.calculate_price(duration_in_minutes)
    p "*" * 100
    p duration_in_minutes
    p "*" * 100
    if duration_in_minutes > 0 && duration_in_minutes <= 5
      duration_in_minutes * 20
    elsif duration_in_minutes > 5 && duration_in_minutes <= 15
      duration_in_minutes * 15
    elsif duration_in_minutes > 15
      duration_in_minutes * 10
    else
      0
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/confirmation.html.erb
<div class="flex flex-col justify-start items-center">
  <div class="film-yourself-block flex flex-col justify-center items-center mt-65 pt-40 pb-40">
    <h4 class="mt-65 video-h4"><%= t('videos.confirmation.skip_step') %></h4>
    <%= image_tag 'icons/plus.png', class: 'image-from-image-text-block' %>

  <div class="mt-8">

    <div class="frame">

      <div class="p-text-18"><%= t('videos.confirmation.invite_friends') %></div>

      <%= form_with url: confirmation_post_path, method: :post, html: { data: {turbo: false}} do |f| %>
        <div class="share-wrapper">
          <%= f.email_field :email, placeholder: "Email", class:"share-email" %>
          <%= f.submit t('invite'), class:"share-submit" %>
        </div>
      <% end %>

      <p class="p-text-16"><%= t('videos.confirmation.share_link') %></p>

      <div class="share-clipboard" data-controller="clipboard">
        <div class="share-clipboard-wrapper">
          <%= image_tag "icons/tabler_link.png" %>
          <span><%= join_url(@video.token) %></span>
        </div>
        <span data-action="click->clipboard#copy" data-clipboard-value-param="<%= join_url(@video.token) %>" class="share-clipboard-btn"><%= t('copy') %></span>
      </div>

    </div>


    <div class="video-steps">
      <%= render "videos/shared/back_button" %>
      <%= link_to t('next_step'), skip_confirmation_path, class: "black-link" %>
    </div>

  </div>
  </div>

</div>

app/views/videos/content_dedicace.html.erb
<div>
  <h1 class="video-h1"><%= t('videos.content_dedicace.preview_available') %></h1>
  <div class="flex flex-row justify-center w-full">
    <%= image_tag 'left-with-star.png', class: 'image-sides left-image' %>
    <div class="content w-full flex flex-col justify-center items-center">

      <div class="edit-video-frame">
        <% if @video.completed? %>
          <div>
            <div class="flex justify-start items-center mb-45">
              <div class="mr-2 p-text-16"><%= t('videos.content_dedicace.your_media') %></div>
              <div class="flex justify-start items-center p-text-16">
                <%= image_tag 'icons/mingcute_time-line.png', alt: 'Time Icon', class: 'inline-block ml-2 mr-2', style: 'height: 24px; width: 24px;' %>
                <%= format_time(@video.final_video_duration) %>
              </div>
              <div class="ml-50"><%= t('videos.content_dedicace.film_cost') %></div>
              <div class="flex justify-start items-center p-text-16">
                <%= image_tag 'icons/ant-design_euro-outlined', alt: 'Time Icon', class: 'inline-block ml-2 mr-2', style: 'height: 24px; width: 24px;' %>
                <%duration_in_minutes = Video.calculate_duration(@video.final_video_duration) %>
                <%=Video.calculate_price(duration_in_minutes)%>
              </div>
            </div>
            <div class="flex justify-start items-center mt-8">
              <div class="mr-2 font-bold"><%= t('videos.content_dedicace.theme') %></div>
              <div class="flex justify-start items-center p-text-16">
                <%=@video&.dedicace&.name%>
              </div>
            </div>
            <video controls style="max-width: 100%; height: auto; border-radius: 20px; margin-top: 20px;">
              <source src="<%= url_for(@video.final_video_with_watermark) %>" type="video/mp4">
              <%= t('videos.content_dedicace.browser_not_supported') %>
            </video>
          </div>
          <%= link_to t('videos.content_dedicace.refresh_video'), content_dedicace_path(refresh: true), class: "transparent-link", data: { disable_with: "Refreshing..." } %>
        <% elsif @video.processing? %>
          <p><%= t('videos.content_dedicace.processing_message') %></p>
        <% else %>
          <p><%= t('videos.content_dedicace.no_final_video') %></p>
        <% end %>
      </div>

      <div class="video-steps w-full">
        <%= link_to t('modify'), step_back_path, class: "transparent-link", data: {turbo: false} %>
        <%= link_to t('pay'), skip_content_dedicace_path, data: { turbo: false }, class: "black-link" %>
      </div>
    </div>
    <%= image_tag 'right-no-star.png', class: 'image-sides right-image' %>
  </div>
</div>


<script>
  document.addEventListener("DOMContentLoaded", function() {
    const video = document.getElementById('video-player');
    const playPauseButton = document.getElementById('play-pause');
    if(playPauseButton){
      playPauseButton.addEventListener('click', () => {
        if (video.paused) {
          video.play();
          playPauseButton.textContent = 'Pause';
          playPauseButton.classList.remove('with-play-icon');
          playPauseButton.classList.add('with-stop-icon');
        } else {
          video.pause();
          playPauseButton.textContent = 'Play';
          playPauseButton.classList.remove('with-stop-icon');
          playPauseButton.classList.add('with-play-icon');
        }
      });
    }

    const videoId = "<%= @video.id %>";

    // Check the initial status of the video
    fetch(`/videos/${videoId}/concat_status`)
      .then(response => response.json())
      .then(data => {
        console.log(data);

        // Only start polling if the video is processing
        if (data.concat_status !== "completed") {
          const intervalId = setInterval(() => {
            checkStatus(intervalId); // Pass the interval ID to clear it later
          }, 10000); // Poll every 10 seconds
        }
      });

    function checkStatus(intervalId) {
      fetch(`/videos/${videoId}/concat_status`)
        .then(response => response.json())
        .then(data => {
          console.log(data);
          if (data.concat_status === "completed") {
            clearInterval(intervalId); // Stop polling
            window.location.reload(); // Reloads the page to show the final video
          }
        })
        .catch(error => {
          console.error("Error checking status:", error);
        });
    }
  });
</script>

app/views/videos/date_fin.html.erb
<div class="date_fin">
  <section class="hero">
    <h1 class="h1-video gradient-text"><%= t('videos.date_fin.title') %></h1>
  </section>
  <div class="flex flex-row justify-center w-full">
    <%= image_tag 'left-no-star.png', class: 'image-sides left-image' %>
    <div class="content w-full flex flex-col justify-center items-center">
      <div class="text-with-image-block-occasion flex justify-center items-center mb-[72px] w-full p-text-16">
        The purpose and deadlines dictum eu morbi ac elit enim at neque urna. Eleifend condimentum ipsum a lectus tortor est arcu. Feugiat lectus auctor cursus netus eu sit in pharetra. Convallis eget odio molestie urna phasellus etiam ac euismod justo. Ipsum tristique purus risus at ultrices non. Eget lectus diam eget feugiat nulla imperdiet ornare libero.
        <%= image_tag 'icons/eight.png', class: 'image-from-image-text-block' %>
      </div>



      <div class="flex justify-center">

        <%= form_with url: date_fin_post_path, method: :post, html: { data: { turbo: false } }  do |f| %>

          <div class="flex-block-container flex flex-col justify-start mb-[48px] relative inline-block w-full">

              <h3 class="text-black text-center font-montserrat text-[32px] font-bold leading-[37px] mb-[24px]"><%= t('videos.date_fin.title') %></h3>
              <p class="p-text-center-16 text-center font-red-hat-display text-[16px] font-normal leading-[25px]"><%= t('videos.date_fin.description') %></p>
              <%# <%= f.date_field :end_date, value: @video.end_date %>
              <div class="flex justify-center">
                <div class="custom-calendar-container mt-65" data-controller="custom-calendar" data-custom-calendar-end-date="<%= @video.end_date %>">
                  <%= hidden_field_tag 'end_date', @video.end_date, id: 'customDateField', data: { custom_calendar_target: "hiddenField" } %>
                  <div id="customCalendar" class="custom-calendar" data-custom-calendar-target="calendarContainer">
                    <!-- The custom calendar will be rendered here by the controller -->
                  </div>
                </div>
              </div>
          </div>

          <div class="flex justify-between">
            <%= render "videos/shared/back_button" %>
            <%= f.submit t('next_step'), class: "black-link" %>
          </div>

        <% end %>

      </div>
    </div>
    <%= image_tag 'right-with-star.png', class: 'image-sides right-image' %>
  </div>
</div>

app/views/videos/destinataire.html.erb
<div>
  <h1 class="video-h1"><%= t('videos.destinataire.title') %></h1>
  <p class="video-desc">Ipsum dolor sit amet consectetur. Dictum eu morbi ac elit enim at neque urna. Eleifend condimentum ipsum a lectus tortor est arcu. Feugiat lectus auctor cursus netus eu sit in pharetra. Convallis eget odio molestie urna phasellus etiam ac euismod justo. Ipsum tristique purus risus at ultrices non. Eget lectus diam eget feugiat nulla imperdiet ornare libero.</p>

  <div class="frame">

    <%= form_with url: destinataire_post_path, method: :post do |f| %>
      <% VideoDestinataire.genres.keys.each do |k| %>
        <div class="">
          <%= f.radio_button 'sexe_destinataire', k  %>
          <%= f.label "sexe_destinataire_#{k}", k.humanize %>
        </div>
      <% end %>

    <%= f.submit t('next_step'), class:"cta" %>
    <% end %>
  </div>
</div>

app/views/videos/join.html.erb
<%if @existing_collaboration.present?%>
  <h1 class="video-h1 mb-150 mt-65"><%= t('videos.join.invitation_accepted') %></h1>
<%else%>
  <h1 class="video-h1 mb-150 mt-65"><%= t('videos.join.login_required') %></h1>
<%end%>

app/views/videos/occasion.html.erb
<div class="video_occasion">
  <section class="hero">
    <h1 class="h1-video gradient-text"><%= t('videos.occasion.title') %></h1>
  </section>

  <div class="flex flex-row justify-center w-full">
    <%= image_tag 'left-with-star.png', class: 'image-sides left-image' %>
    <div class="content w-full flex flex-col justify-center items-center">
      <div class="text-with-image-block-occasion flex justify-center items-center mb-[72px] w-full p-text-16">
        Ipsum dolor sit amet consectetur. Dictum eu morbi ac elit enim at neque urna. Eleifend condimentum ipsum a lectus tortor est arcu. Feugiat lectus auctor cursus netus eu sit in pharetra. Convallis eget odio molestie urna phasellus etiam ac euismod justo. Ipsum tristique purus risus at ultrices non. Eget lectus diam eget feugiat nulla imperdiet ornare libero.
        <%= image_tag 'icons/occasion-icon.png', class: 'image-from-image-text-block-occasion' %>
      </div>

      <div class="flex justify-center">

        <%= form_with url: occasion_post_path, method: :post, html: { data: { turbo: false } }  do |f| %>

          <div class="occasion mb-[48px] relative inline-block w-full">

            <div class="relative inline-block w-full mb-[199px]">
              <%= f.select :occasion, options_for_select(Video.occasions.map {|k, v| [k.humanize.capitalize, k]}), {}, class: "appearance-none w-full px-4 py-2 pr-10 bg-white border border-gray-300 rounded-lg shadow-sm focus:outline-none focus:border-blue-500" %>
              <%= inline_svg_tag 'icons/select-down.svg', class: 'absolute right-[40px] top-1/2 transform -translate-y-1/2 w-[15px] h-[15px] object-contain object-center pointer-events-none' %>
            </div>

            <div class="flex items-center gap-[23px]">
                <%= image_tag "icons/attention.svg" %>
                <p class="p-text-16"><%= t('videos.occasion.soon_available') %></p>
            </div>
          </div>

          <div class="flex justify-between">
            <%= render "videos/shared/back_button" %>
            <%= f.submit t('next_step'), class: "black-link" %>
          </div>

        <% end %>

      </div>
    </div>
    <%= image_tag 'right-no-star.png', class: 'image-sides right-image' %>
  </div>

</div>

app/views/videos/share.html.erb
<div>

  <%if @video.colab?%>
    <h1 class="video-h1"><%= t('videos.share.title_colab') %></h1>
  <%else%>
    <h1 class="video-h1"><%= t('videos.share.title_solo') %></h1>
  <%end%>

  <div class="flex flex-row justify-center w-full">
    <%= image_tag 'left-no-star.png', class: 'image-sides left-image' %>
    <div class="content w-full flex flex-col justify-center items-center">
      <div class="text-with-image-block padding-sides-120 text-center flex justify-center items-center mb-[72px] w-full p-text-center-16">
        <%if @video.colab?%>
          <%= t('videos.share.description_colab') %>
        <%else%>
          <%= t('videos.share.description_solo') %>
        <%end%>
        <%= image_tag 'icons/green-plus.png', class: 'image-from-image-text-block' %>
      </div>


      <div class="">

        <div class="frame">

          <h4 class="video-h4"><%= t('videos.share.invitation_header') %></h4>

          <%= form_with url: share_post_path, method: :post do |f| %>
            <div class="share-wrapper">
              <%= f.email_field :email, placeholder: "Email", class:"share-email" %>
              <%= f.submit t('invite'), class:"share-submit" %>
            </div>
          <% end %>

          <p class="p-text-16"><%= t('videos.share.share_link') %></p>

          <div class="share-clipboard" data-controller="clipboard">
            <div class="share-clipboard-wrapper">
              <%= image_tag "icons/tabler_link.png" %>
              <span><%= join_url(@video.token) %></span>
            </div>
            <span data-action="click->clipboard#copy" data-clipboard-value-param="<%= join_url(@video.token) %>" class="share-clipboard-btn"><%= t('copy') %></span>
          </div>

          <div class="flex flex-row justify-center items-center">
            <%= image_tag "icons/whats-share.png", class: 'share-icon-whats'%>
            <%= image_tag "icons/facebook-share.png", class: 'share-icon-facebook' %>
          </div>
        </div>

        <div class="video-alert">
          <%= image_tag "icons/alert.svg" %>
          <p class="p-text-16"><%= t('videos.share.skip_step_warning') %></p>
        </div>

        <div class="video-steps">
          <%= render "videos/shared/back_button" %>
          <%= link_to t('next_step'), skip_share_path, data: {turbo: false}, class: "black-link" %>
        </div>
      </div>
    </div>
    <%= image_tag 'right-with-star.png', class: 'image-sides right-image' %>
  </div>
</div>