config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  scope "(:locale)", locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users
    resources :users, only: %i[show edit update] # Add other actions if needed

    post "flush_and_reseed", to: "static#flush_and_reseed"
    # resources :contacts, only: [:new, :create]

    resources :contacts, only: %i[new create]

    # Video
    get "videos/back", to: "videos#go_back", as: "step_back"
    get "videos/go_to_select_chapters", to: "videos#go_to_select_chapters", as: "go_to_select_chapters"

    get "videos/start", to: "videos#start", as: "start"
    post "videos/start", to: "videos#start_post", as: "start_post"

    get "videos/occasion", to: "videos#occasion", as: "occasion"
    post "videos/occasion", to: "videos#occasion_post", as: "occasion_post"

    # get 'videos/destinataire', to: "videos#destinataire", as: "destinataire"
    # post 'videos/destinataire', to: "videos#destinataire_post", as: "destinataire_post"

    get "videos/info_destinataire", to: "videos#info_destinataire", as: "info_destinataire"
    post "videos/info_destinataire", to: "videos#info_destinataire_post", as: "info_destinataire_post"

    get "videos/destinataire_details", to: "videos#destinataire_details", as: "destinataire_details"
    post "videos/destinataire_details_post", to: "videos#destinataire_details_post", as: "destinataire_details_post"
    delete "videos/delete_destinataire/:id", to: "videos#delete_destinataire", as: "delete_destinataire"
    patch "videos/update_destinataire/:id", to: "videos#update_destinataire", as: "update_destinataire"

    get "videos/date_fin", to: "videos#date_fin", as: "date_fin"
    post "videos/date_fin", to: "videos#date_fin_post", as: "date_fin_post"

    get "videos/introduction", to: "videos#introduction", as: "introduction"
    post "videos/introduction", to: "videos#introduction_post", as: "introduction_post"

    get "videos/photo_intro", to: "videos#photo_intro", as: "photo_intro"
    post "videos/photo_intro", to: "videos#photo_intro_post", as: "photo_intro_post"
    delete "videos/drop_preview/:id", to: "videos#drop_preview", as: "drop_preview"

    get "videos/select_chapters", to: "videos#select_chapters", as: "select_chapters"
    post "videos/select_chapters", to: "videos#select_chapters_post", as: "select_chapters_post"

    get "videos/music", to: "videos#music", as: "music"
    post "videos/music", to: "videos#music_post", as: "music_post"
    patch "videos/update_video_music_type", to: "videos#update_video_music_type", as: "update_video_music_type"
    delete "videos/drop_custom_music/:id", to: "videos#drop_custom_music", as: "drop_custom_music"

    get "videos/dedicace", to: "videos#dedicace", as: "dedicace"
    post "videos/dedicace", to: "videos#dedicace_post", as: "dedicace_post"

    get "videos/share", to: "videos#share", as: "share"
    post "videos/share", to: "videos#share_post", as: "share_post"
    get "videos/skip_share", to: "videos#skip_share", as: "skip_share"

    get "videos/content", to: "videos#content", as: "content"
    post "videos/content", to: "videos#content_post", as: "content_post"
    get "videos/skip_content", to: "videos#skip_content", as: "skip_content"

    get "videos/content_dedicace", to: "videos#content_dedicace", as: "content_dedicace"
    get "videos/:id/stream", to: "videos#stream_video", as: "stream_video"
    post "videos/content_dedicace", to: "videos#content_dedicace_post", as: "content_dedicace_post"
    get "videos/skip_content_dedicace", to: "videos#skip_content_dedicace", as: "skip_content_dedicace"

    get "videos/deadline", to: "videos#deadline", as: "deadline"
    post "videos/deadline", to: "videos#deadline_post", as: "deadline_post"
    get "videos/skip_deadline", to: "videos#skip_deadline", as: "skip_deadline"

    get "videos/dedicace_de_fin", to: "videos#dedicace_de_fin", as: "dedicace_de_fin"
    patch "/:id/videos/dedicace_de_fin_post", to: "videos#dedicace_de_fin_post", as: "dedicace_de_fin_post"
    get "videos/skip_dedicace_de_fin", to: "videos#skip_dedicace_de_fin", as: "skip_dedicace_de_fin"

    get "videos/confirmation", to: "videos#confirmation", as: "confirmation"
    post "videos/confirmation", to: "videos#confirmation_post", as: "confirmation_post"
    get "videos/skip_confirmation", to: "videos#skip_confirmation", as: "skip_confirmation"

    patch "videos/:id/update_video_slot", to: "videos#update_video_slot", as: "update_video_slot"

    get "videos/:id/get_video_slot_status", to: "videos#get_video_slot_status", as: "get_video_slot_status"

    get "videos/edit_video", to: "videos#edit_video", as: "edit_video"
    post "videos/edit_video_post", to: "videos#edit_video_post", as: "edit_video_post"
    get "videos/skip_edit_video", to: "videos#skip_edit_video", as: "skip_edit_video"
    delete "videos/delete_video_chapter/:id", to: "videos#delete_video_chapter", as: "delete_video_chapter"
    delete "videos/purge_chapter_attachment/:id", to: "videos#purge_chapter_attachment", as: "purge_chapter_attachment"

    get "videos/payment", to: "videos#payment", as: "payment"
    post "videos/payment_post", to: "videos#payment_post", as: "payment_post"

    get "videos/render_final_page", to: "videos#render_final_page", as: "render_final_page"

    get "join/videos/:id", to: "videos#join", as: "join"

    get "projects/as_creator", to: "projects#as_creator_projects", as: "as_creator_projects"
    get "projects/as_collaborator", to: "projects#as_collaborator_projects", as: "as_collaborator_projects"
    get "projects/participants_progress", to: "projects#participants_progress", as: "participants_progress"
    get "projects/collaborator_video_details/:id", to: "projects#collaborator_video_details",
                                                   as: "collaborator_video_details"

    get "projects/collaborator_manage_chapters/:id", to: "projects#collaborator_manage_chapters",
                                                     as: "collaborator_manage_chapters"
    get "projects/collaborator_manage_dedicace/:id", to: "projects#collaborator_manage_dedicace",
                                                     as: "collaborator_manage_dedicace"
    post "projects/collaborator_chapters_post", to: "projects#collaborator_chapters_post",
                                                as: "collaborator_chapters_post"
    post "projects/edit_collaborator_chapters_post", to: "projects#edit_collaborator_chapters_post",
                                                     as: "edit_collaborator_chapters_post"
    delete "projects/delete_collaborator_chapter/:id", to: "projects#delete_collaborator_chapter",
                                                       as: "delete_collaborator_chapter"
    post "projects/collaborator_dedicace_de_fin_post", to: "projects#collaborator_dedicace_de_fin_post",
                                                       as: "collaborator_dedicace_de_fin_post"

    get "projects/creator_manage_chapters/:id", to: "projects#creator_manage_chapters", as: "creator_manage_chapters"
    get "projects/creator_manage_dedicace/:id", to: "projects#creator_manage_dedicace", as: "creator_manage_dedicace"
    post "projects/creator_chapters_post", to: "projects#creator_chapters_post", as: "creator_chapters_post"
    post "projects/edit_creator_chapters_post", to: "projects#edit_creator_chapters_post",
                                                as: "edit_creator_chapters_post"
    delete "projects/delete_creator_chapter/:id", to: "projects#delete_creator_chapter", as: "delete_creator_chapter"
    post "projects/creator_dedicace_de_fin_post", to: "projects#creator_dedicace_de_fin_post",
                                                  as: "creator_dedicace_de_fin_post"
    post "projects/creator_refresh_video", to: "projects#creator_refresh_video", as: "creator_refresh_video"
    post "projects/approving_collaborator_attachments", to: "projects#approving_collaborator_attachments",
                                                        as: "approving_collaborator_attachments"
    get "projects/invite_collaborators", to: "projects#invite_collaborators", as: "invite_collaborators"
    post "projects/invite_collaborators_post", to: "projects#invite_collaborators_post", as: "invite_collaborators_post"

    delete "projects/delete_collaboration/:id", to: "projects#delete_collaboration", as: "delete_collaboration"
    patch "projects/:id/modify_deadline", to: "projects#modify_deadline", as: "modify_deadline"
    patch "projects/:id/close_project", to: "projects#close_project", as: "close_project"

    get "videos/:id/concat_status", to: "videos#concat_status", as: "video_concat_status"

    # Static pages
    get "about", to: "static#about", as: "about"
    get "pricing", to: "static#pricing", as: "pricing"

    # Users profile pages
    get "profile", to: "users#show", as: :profile

    # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
    # Can be used by load balancers and uptime monitors to verify that the app is live.
    get "up" => "rails/health#show", as: :rails_health_check

    # Defines the root path route ("/")
    root "static#home"
  end
end

app/views/shared/_creator_participant_block.html.erb
  <div class="flex flex-row items-start">
    <div class='<%= creator ? "link-projects" : "active-link-projects" %>'><%= link_to "Je suis un participant", as_collaborator_projects_path, class: 'block w-full h-full' %></div>
    <div class='<%= creator ? "active-link-projects" : "link-projects" %> ml-2'><%= link_to 'Je suis un créateur', as_creator_projects_path, class: 'block w-full h-full ' %></div>
  </div>

app/views/shared/_faq.html.erb
<section id="faq">
    <h2 class="relative"><%= t('faq.title') %></h2>
    <p class="p-text-18"><%= t('faq.description') %></p>

    <div class="faq-section">
        <article class="faq-item">
            <header class="faq-question" aria-expanded="true">
                <h3 class="gradient-text"><%= t('faq.questions.what_is_emotion.question') %></h3>
                <%= image_tag "icons/chevron-up.svg", alt: t('faq.chevron_up'), class: "chevron" %>
            </header>
            <div class="faq-answer">
                <p class="p-text-16"><%= t('faq.questions.what_is_emotion.answer') %></p>
            </div>
        </article>
        <article class="faq-item">
            <header class="faq-question" aria-expanded="false">
                <h3 class="gradient-text"><%= t('faq.questions.what_is_emotion_alt.question') %></h3>
                <%= image_tag "icons/chevron-down.svg", alt: t('faq.chevron_down'), class: "chevron" %>
            </header>
            <div class="faq-answer hidden">
                <p class="p-text-16"><%= t('faq.questions.what_is_emotion_alt.answer') %></p>
            </div>
        </article>
        <article class="faq-item">
            <header class="faq-question" aria-expanded="false">
                <h3 class="gradient-text"><%= t('faq.questions.video_cost.question') %></h3>
                <%= image_tag "icons/chevron-down.svg", alt: t('faq.chevron_down'), class: "chevron" %>
            </header>
            <div class="faq-answer hidden">
                <p class="p-text-16"><%= t('faq.questions.video_cost.answer') %></p>
            </div>
        </article>
        <article class="faq-item">
            <header class="faq-question" aria-expanded="false">
                <h3 class="gradient-text"><%= t('faq.questions.after_payment.question') %></h3>
                <%= image_tag "icons/chevron-down.svg", alt: t('faq.chevron_down'), class: "chevron" %>
            </header>
            <div class="faq-answer hidden">
                <p class="p-text-16"><%= t('faq.questions.after_payment.answer') %></p>
            </div>
        </article>
        <article class="faq-item">
            <header class="faq-question" aria-expanded="false">
                <h3 class="gradient-text"><%= t('faq.questions.payment_methods.question') %></h3>
                <%= image_tag "icons/chevron-down.svg", alt: t('faq.chevron_down'), class: "chevron" %>
            </header>
            <div class="faq-answer hidden">
                <p class="p-text-16"><%= t('faq.questions.payment_methods.answer') %></p>
            </div>
        </article>
        <article class="faq-item">
            <header class="faq-question" aria-expanded="false">
                <h3 class="gradient-text"><%= t('faq.questions.pay_after_creation.question') %></h3>
                <%= image_tag "icons/chevron-down.svg", alt: t('faq.chevron_down'), class: "chevron" %>
            </header>
            <div class="faq-answer hidden">
                <p class="p-text-16"><%= t('faq.questions.pay_after_creation.answer') %></p>
            </div>
        </article>
        <article class="faq-item">
            <header class="faq-question" aria-expanded="false">
                <h3 class="gradient-text"><%= t('faq.questions.invite_people.question') %></h3>
                <%= image_tag "icons/chevron-down.svg", alt: t('faq.chevron_down'), class: "chevron" %>
            </header>
            <div class="faq-answer hidden">
                <p class="p-text-16"><%= t('faq.questions.invite_people.answer') %></p>
            </div>
        </article>
    </div>
</section>

<script>
document.addEventListener("DOMContentLoaded", function() {
    const items = document.querySelectorAll(".faq-item");

    function toggleAccordion() {
        const itemToggle = this.getAttribute('aria-expanded');

        items.forEach(item => {
            const question = item.querySelector('.faq-question');
            const answer = item.querySelector('.faq-answer');
            const chevron = question.querySelector('.chevron');

            question.setAttribute('aria-expanded', 'false');
            answer.classList.add('hidden');
            answer.style.maxHeight = null;
            chevron.src = '<%= asset_path("icons/chevron-down.svg") %>';
        });

        if (itemToggle === 'false') {
            this.setAttribute('aria-expanded', 'true');
            const answer = this.nextElementSibling;
            const chevron = this.querySelector('.chevron');
            answer.classList.remove('hidden');
            answer.style.maxHeight = answer.scrollHeight + 'px';
            chevron.src = '<%= asset_path("icons/chevron-up.svg") %>';
        }
    }

    items.forEach(item => {
        item.querySelector('.faq-question').addEventListener('click', toggleAccordion);
    });

    // Initialize the first item as expanded
    if (items.length > 0) {
        const firstQuestion = items[0].querySelector('.faq-question');
        const firstAnswer = items[0].querySelector('.faq-answer');
        const firstChevron = items[0].querySelector('.faq-question .chevron');

        firstQuestion.setAttribute('aria-expanded', 'true');
        firstAnswer.classList.remove('hidden');
        firstAnswer.style.maxHeight = firstAnswer.scrollHeight + 'px';
        firstChevron.src = '<%= asset_path("icons/chevron-up.svg") %>';
    }
});
</script>

<style>

#faq {
    padding: 64px 0 80px;
}

#faq h2 {
    margin-bottom: 24px;
}

#faq h2::before {
    content: "";
    background-image: url('<%= asset_path("gemotion-faq-light.png") %>');
    background-size: contain;
    background-position: center;
    background-repeat: no-repeat;
    position: absolute;
    display: block;
    width: 200px;
    height: 200px;
    right: -120px;
    top: -70px;
}

#faq p {
    margin-bottom: 48px;
}

.faq-section {
    width: 100%;
    height: 100%;
    padding: 48px;
    background: white;
    box-shadow: 4px 4px 20px 5px rgba(12.69, 102.84, 131.31, 0.1);
    border-radius: 20px;
    display: flex;
    flex-direction: column;
    justify-content: flex-start;
    align-items: flex-start;
    gap: 24px;
    max-width: 1062px;
    position: relative; /* Required for absolute positioning of pseudo-elements */
}

.faq-section::before {
  content: "";
  position: absolute;
  top: 0px;
  left: 0px;
  width: 100%;
  height: 100%;
  border-radius: 20px;
  background: linear-gradient(205.68deg, #C9E1FF 19.49%, #0D6783 60.63%, #163F50 90.92%);
  z-index: 0;
}

.faq-section::after {
  content: "";
  position: absolute;
  top: 2px; /* Matches border thickness */
  left: 2px; /* Matches border thickness */
  width: calc(100% - 4px); /* Adjust width for border thickness */
  height: calc(100% - 4px); /* Adjust height for border thickness */
  border-radius: 18px; /* Inner radius: subtract border thickness */
  background: white; /* Matches block background */
  z-index: 0; /* Above the gradient but behind content */
}

.faq-section > * {
  position: relative; /* Ensure content stays above pseudo-elements */
  z-index: 1;
}

.faq-section[aria-expanded="true"] {
    background: inherit;
    color: inherit;
}

.faq-section h3 {
    font-size: 20px;
    font-family: "Montserrat";
    font-weight: 700;
    line-height: 24px;
    word-wrap: break-word;
}

.faq-section p {
    color: #201f1f;
    font-size: 16px;
    font-weight: 400;
    line-height: 25px;
    word-wrap: break-word;
}

.faq-section article.faq-item {
    display: flex;
    flex-direction: column;
    gap: 20px;
    width: 100%;
    border-top: 1px solid rgba(0, 0, 0, 0.20);
    padding-top: 24px;
}

.faq-question {
    cursor: pointer;
    border-radius: 5px;
    transition: background 0.3s ease, color 0.3s ease;
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.faq-answer {
    max-height: 0;
    overflow: hidden;
    transition: max-height 0.5s ease-out, padding 0.5s ease;
}

.hidden {
    max-height: 0 !important;
    padding: 0 !important;
}
</style>

app/views/shared/_footer.html.erb
<footer>
  <section id="footer" class="py-12">
    <div class="w-[1280px] mx-auto flex justify-between items-start">
      <%= link_to root_path do %>
        <%= image_tag 'gemotion-logo-footer.svg', alt: 'Gemotion Logo' %>
      <% end %>
      <div id="footer_contacts">
        <p class="text-title-color text-xl font-montserrat font-bold leading-6 break-words mb-[20px] gradient-text"><%= t('footer.contacts') %></p>
        <nav>
          <ul class="flex flex-col gap-[14px]">
            <li class="flex items-center gap-[6px]">
              <%= link_to "mailto:email@gmail.com", aria: { label: t('footer.email_aria_label') } do %>
                <%= image_tag "icons/email.svg", alt: t('footer.email_icon_alt') %>
              <% end %>
              <%= link_to "email@gmail.com", "mailto:email@gmail.com", class: "p-text-16", aria: { label: t('footer.email_aria_label') } %>
            </li>
            <li class="flex items-center gap-[6px]">
              <%= link_to "tel:0000000", aria: { label: t('footer.phone_aria_label') } do %>
                <%= image_tag "icons/phone.svg", alt: t('footer.phone_icon_alt') %>
              <% end %>
              <%= link_to "000-000-000", "tel:0000000", class: "p-text-16", aria: { label: t('footer.phone_aria_label') } %>
            </li>
          </ul>
        </nav>
      </div>
      <div id="footer_inscription">
        <p class="text-title-color text-xl font-montserrat font-bold leading-6 break-words mb-[12px] gradient-text"><%= t('footer.registration') %></p>
        <nav>
          <ul class="flex flex-col gap-[5px]">
            <li><%= link_to t('footer.create_account'), root_path, class: "p-text-16" %></li>
            <li><%= link_to t('footer.sign_in'), root_path, class: "p-text-16" %></li>
            <li><%= link_to t('footer.contact_us'), new_contact_path, class: "p-text-16" %></li>
          </ul>
        </nav>
      </div>
      <div id="footer_video">
        <p class="text-title-color text-xl font-montserrat font-bold leading-6 break-words mb-[12px] gradient-text"><%= t('footer.create_video') %></p>
        <nav>
          <ul class="flex flex-col gap-[5px]">
            <li><%= link_to t('footer.get_started'), start_path(continue: true), class: "p-text-16" %></li>
            <li><%= link_to t('footer.how_it_works'), about_path, class: "p-text-16" %></li>
            <li><%= link_to t('footer.pricing'), pricing_path, class: "p-text-16" %></li>
          </ul>
        </nav>
      </div>
      <div id="footer_socials">
        <p class="text-title-color text-xl font-montserrat font-bold leading-6 break-words mb-[23px] gradient-text"><%= t('footer.socials') %></p>
        <nav>
          <ul class="flex flex-row items-center gap-[11px]">
            <li>
              <%= link_to "https://instagram.com", target: "_blank", aria: { label: t('footer.instagram_aria_label') } do %>
                <%= image_tag "icons/InstagramLogo.png", alt: t('footer.instagram_icon_alt'), class: "instagram-icon" %>
              <% end %>
            </li>
            <li>
              <%= link_to "https://facebook.com", target: "_blank", aria: { label: t('footer.facebook_aria_label') } do %>
                <%= image_tag "icons/facebook1.png", alt: t('footer.facebook_icon_alt'), class: "facebook-icon"  %>
              <% end %>
            </li>
            <li>
              <%= link_to "https://twitter.com", target: "_blank", aria: { label: t('footer.twitter_aria_label') } do %>
                <%= image_tag "icons/twitter1.png", alt: t('footer.twitter_icon_alt'), class: "twitter-icon"  %>
              <% end %>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </section>

  <section id="copyright" class="py-4 bg-shared-bg">
    <p class="text-white text-base font-red-hat-display font-normal leading-[25px] break-words text-center">
      <%= t('footer.copyright_text') %>
      <%= link_to t('footer.agency_name'), "https://digitality-agency.com", target: "_blank", class: "text-white" %>
    </p>
  </section>
</footer>

app/views/shared/_header.html.erb
<header class="py-4 bg-shared-bg-blue sticky top-0 z-50">
  <div class="w-[1280px] mx-auto flex justify-between items-center">
    <%= link_to root_path, data: { turbo: false } do %>
      <%= image_tag 'gemotion-logo-header.svg', alt: 'Gemotion Logo' %>
    <% end %>

    <nav id="primary_menu" class="flex space-x-8">
      <ul class="flex space-x-8">
        <li>
          <%= link_to t('header.home'), root_path, class: "text-white text-lg font-montserrat font-bold uppercase leading-7 break-words", data: { turbo: false }  %>
        </li>
        <li>
          <%= link_to t('header.how_it_works'), about_path, class: "text-white text-lg font-montserrat font-bold uppercase leading-7 break-words", data: { turbo: false }  %>
        </li>
        <li>
          <%= link_to t('header.pricing'), pricing_path, class: "text-white text-lg font-montserrat font-bold uppercase leading-7 break-words", data: { turbo: false }  %>
        </li>
      </ul>
    </nav>

    <nav id="secondary_menu" class="flex space-x-8">
      <ul class="flex items-center gap-2">
        <li class="text-white flex gap-2">
          <% Rails.application.config.i18n.available_locales.each_with_index do | locale, index | %>
            <%= link_to t(Rails.application.config.i18n.available_locales[index]), :locale => locale %> <%= " |" if index != Rails.application.config.i18n.available_locales.size - 1 %>
          <% end %>
        </li>
        <li>
          <% if user_signed_in? %>
            <%= link_to profile_path do %>
              <%= image_tag "icons/profile.svg", alt: "Profile"%>
            <% end %>
          <% else %>
            <%= link_to new_user_session_path do %>
              <%= image_tag "icons/profile.svg", alt: "Login"%>
            <% end %>
          <% end %>
        </li>
        <li class="flex items-center h-full">
          <%= link_to t('header.start'), start_path(continue: true), class: "text-black text-lg font-montserrat font-bold leading-7 break-words w-full h-full bg-white rounded-[15px] px-[28.32px] pt-[14.43px] pb-[16.78px] flex items-center justify-center" %>
        </li>
        <% if Rails.env.development? %>
          <li class="flex items-center h-full">
            <%= button_to t('buttons.reset'),
                          flush_and_reseed_path,
                          method: :post,
                          class: 'p-2 rounded bg-red-500 text-white',
                          data: {
                            confirm: t('buttons.confirm_reset'),
                            testid: 'app_reset_button'
                          }
            %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/shared/_hello_block.html.erb
<div class="hello-block flex items-center justify-center">
  <h1 class="video-h1">Hello, <%= current_user.full_name%>!</h1>
</div>

app/views/shared/_pricing.html.erb
<section class="pricing-table pb-[56px]">
  <p class="max-w-[837px] mx-auto text-center mb-[48px] p-text-18">
    Le coût de votre vidéo est basé sur sa durée. Faites des prévisualisations gratuites et payez seulement à la fin lorsque vous êtes complètement satisfait et prêt à finaliser votre cadeau vidéo.
  </p>
  <div class="w-[1280px] mx-auto flex justify-center items-start gap-[67px]  mb-[48px]">
    <!-- Card 1 -->
    <div class="pricing-card bg-white shadow-lg rounded-lg p-6 flex flex-col items-center max-w-[309px]">
      <%= image_tag 'gemotion-home-price-img.png', alt: 'Image 1', class: 'mb-4' %>
      <p class="price text-xl font-bold mb-2">€20/min</p>
      <div class="duration text-center">
        <p class="label text-sm font-medium text-gray-600">Durée</p>
        <p class="value text-lg font-bold text-gray-900">0:00-5:00 min</p>
      </div>
    </div>
    <!-- Card 2 -->
    <div class="pricing-card bg-white shadow-lg rounded-lg p-6 flex flex-col items-center max-w-[309px]">
      <%= image_tag 'gemotion-home-price-img.png', alt: 'Image 2', class: 'mb-4' %>
      <p class="price text-xl font-bold mb-2">€15/min</p>
      <div class="duration text-center">
        <p class="label text-sm font-medium text-gray-600">Durée</p>
        <p class="value text-lg font-bold text-gray-900">5:00-15:00 min</p>
      </div>
    </div>
    <!-- Card 3 -->
    <div class="pricing-card bg-white shadow-lg rounded-lg p-6 flex flex-col items-center max-w-[309px]">
      <%= image_tag 'gemotion-home-price-img.png', alt: 'Image 3', class: 'mb-4' %>
      <p class="price text-xl font-bold mb-2">€10/min</p>
      <div class="duration text-center">
        <p class="label text-sm font-medium text-gray-600">Durée</p>
        <p class="value text-lg font-bold text-gray-900">After 15 min</p>
      </div>
    </div>
  </div>
  <%= link_to "Créer une vidéo", start_path, class: "black-link create-video-link" %>
</section>

app/views/shared/_profile_tabs.html.erb
  <div class="choose-prof-block flex items-center justify-between mt-6 px-[16px]">
    <div class="choose-prof-block-child <%= 'choose-prof-block-child-highlight' if page_count == 0 %>">
      <%= link_to 'Détails du profil', profile_path, class: 'block w-full h-full' %>
    </div>
    <div class="choose-prof-block-child <%= 'choose-prof-block-child-highlight' if page_count == 1 %>">
      <%= link_to 'Projets en cours', as_creator_projects_path, class: 'block w-full h-full' %>
    </div>
    <div class="choose-prof-block-child <%= 'choose-prof-block-child-highlight' if page_count == 2 %>">
      <%= button_to 'Se déconnecter', destroy_user_session_path, method: :delete, class: 'block w-full h-full' %>
    </div>
  </div>

app/views/shared/_questions.html.erb
<section id="questions" class="py-[104px] bg-[#F2FCFF]">
    <h2 class="mb-[16px]">Encore des questions ?</h2>
    <p class="mb-[24px] p-text-18">Contactez-nous pour obtenir de l'aide supplémentaire.</p>
    <%= link_to "Contactez-nous", new_contact_path, class: "black-link" %>
</section>

<style>

#questions {
  background-image: url('<%= asset_path("gemotion-questions-bg.png") %>');
  background-position: center 80%;
  background-repeat: no-repeat;
  background-size: cover;
}

</style>