config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  scope "(:locale)", locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users
    resources :users, only: %i[show edit update] # Add other actions if needed

    post "flush_and_reseed", to: "static#flush_and_reseed"
    # resources :contacts, only: [:new, :create]

    resources :contacts, only: %i[new create]

    # Video
    get "videos/back", to: "videos#go_back", as: "step_back"
    get "videos/go_to_select_chapters", to: "videos#go_to_select_chapters", as: "go_to_select_chapters"

    get "videos/start", to: "videos#start", as: "start"
    post "videos/start", to: "videos#start_post", as: "start_post"

    get "videos/occasion", to: "videos#occasion", as: "occasion"
    post "videos/occasion", to: "videos#occasion_post", as: "occasion_post"

    # get 'videos/destinataire', to: "videos#destinataire", as: "destinataire"
    # post 'videos/destinataire', to: "videos#destinataire_post", as: "destinataire_post"

    get "videos/info_destinataire", to: "videos#info_destinataire", as: "info_destinataire"
    post "videos/info_destinataire", to: "videos#info_destinataire_post", as: "info_destinataire_post"

    get "videos/destinataire_details", to: "videos#destinataire_details", as: "destinataire_details"
    post "videos/destinataire_details_post", to: "videos#destinataire_details_post", as: "destinataire_details_post"
    delete "videos/delete_destinataire/:id", to: "videos#delete_destinataire", as: "delete_destinataire"
    patch "videos/update_destinataire/:id", to: "videos#update_destinataire", as: "update_destinataire"

    get "videos/date_fin", to: "videos#date_fin", as: "date_fin"
    post "videos/date_fin", to: "videos#date_fin_post", as: "date_fin_post"

    get "videos/introduction", to: "videos#introduction", as: "introduction"
    post "videos/introduction", to: "videos#introduction_post", as: "introduction_post"

    get "videos/photo_intro", to: "videos#photo_intro", as: "photo_intro"
    post "videos/photo_intro", to: "videos#photo_intro_post", as: "photo_intro_post"
    delete "videos/drop_preview/:id", to: "videos#drop_preview", as: "drop_preview"

    get "videos/select_chapters", to: "videos#select_chapters", as: "select_chapters"
    post "videos/select_chapters", to: "videos#select_chapters_post", as: "select_chapters_post"

    get "videos/music", to: "videos#music", as: "music"
    post "videos/music", to: "videos#music_post", as: "music_post"
    patch "videos/update_video_music_type", to: "videos#update_video_music_type", as: "update_video_music_type"
    delete "videos/drop_custom_music/:id", to: "videos#drop_custom_music", as: "drop_custom_music"

    get "videos/dedicace", to: "videos#dedicace", as: "dedicace"
    post "videos/dedicace", to: "videos#dedicace_post", as: "dedicace_post"

    get "videos/share", to: "videos#share", as: "share"
    post "videos/share", to: "videos#share_post", as: "share_post"
    get "videos/skip_share", to: "videos#skip_share", as: "skip_share"

    get "videos/content", to: "videos#content", as: "content"
    post "videos/content", to: "videos#content_post", as: "content_post"
    get "videos/skip_content", to: "videos#skip_content", as: "skip_content"

    get "videos/content_dedicace", to: "videos#content_dedicace", as: "content_dedicace"
    get "videos/:id/stream", to: "videos#stream_video", as: "stream_video"
    post "videos/content_dedicace", to: "videos#content_dedicace_post", as: "content_dedicace_post"
    get "videos/skip_content_dedicace", to: "videos#skip_content_dedicace", as: "skip_content_dedicace"

    get "videos/deadline", to: "videos#deadline", as: "deadline"
    post "videos/deadline", to: "videos#deadline_post", as: "deadline_post"
    get "videos/skip_deadline", to: "videos#skip_deadline", as: "skip_deadline"

    get "videos/dedicace_de_fin", to: "videos#dedicace_de_fin", as: "dedicace_de_fin"
    patch "/:id/videos/dedicace_de_fin_post", to: "videos#dedicace_de_fin_post", as: "dedicace_de_fin_post"
    get "videos/skip_dedicace_de_fin", to: "videos#skip_dedicace_de_fin", as: "skip_dedicace_de_fin"

    get "videos/confirmation", to: "videos#confirmation", as: "confirmation"
    post "videos/confirmation", to: "videos#confirmation_post", as: "confirmation_post"
    get "videos/skip_confirmation", to: "videos#skip_confirmation", as: "skip_confirmation"

    patch "videos/:id/update_video_slot", to: "videos#update_video_slot", as: "update_video_slot"

    get "videos/:id/get_video_slot_status", to: "videos#get_video_slot_status", as: "get_video_slot_status"

    get "videos/edit_video", to: "videos#edit_video", as: "edit_video"
    post "videos/edit_video_post", to: "videos#edit_video_post", as: "edit_video_post"
    get "videos/skip_edit_video", to: "videos#skip_edit_video", as: "skip_edit_video"
    delete "videos/delete_video_chapter/:id", to: "videos#delete_video_chapter", as: "delete_video_chapter"
    delete "videos/purge_chapter_attachment/:id", to: "videos#purge_chapter_attachment", as: "purge_chapter_attachment"

    get "videos/payment", to: "videos#payment", as: "payment"
    post "videos/payment_post", to: "videos#payment_post", as: "payment_post"

    get "videos/render_final_page", to: "videos#render_final_page", as: "render_final_page"

    get "join/videos/:id", to: "videos#join", as: "join"

    get "projects/as_creator", to: "projects#as_creator_projects", as: "as_creator_projects"
    get "projects/as_collaborator", to: "projects#as_collaborator_projects", as: "as_collaborator_projects"
    get "projects/participants_progress", to: "projects#participants_progress", as: "participants_progress"
    get "projects/collaborator_video_details/:id", to: "projects#collaborator_video_details",
                                                   as: "collaborator_video_details"

    get "projects/collaborator_manage_chapters/:id", to: "projects#collaborator_manage_chapters",
                                                     as: "collaborator_manage_chapters"
    get "projects/collaborator_manage_dedicace/:id", to: "projects#collaborator_manage_dedicace",
                                                     as: "collaborator_manage_dedicace"
    post "projects/collaborator_chapters_post", to: "projects#collaborator_chapters_post",
                                                as: "collaborator_chapters_post"
    post "projects/edit_collaborator_chapters_post", to: "projects#edit_collaborator_chapters_post",
                                                     as: "edit_collaborator_chapters_post"
    delete "projects/delete_collaborator_chapter/:id", to: "projects#delete_collaborator_chapter",
                                                       as: "delete_collaborator_chapter"
    post "projects/collaborator_dedicace_de_fin_post", to: "projects#collaborator_dedicace_de_fin_post",
                                                       as: "collaborator_dedicace_de_fin_post"

    get "projects/creator_manage_chapters/:id", to: "projects#creator_manage_chapters", as: "creator_manage_chapters"
    get "projects/creator_manage_dedicace/:id", to: "projects#creator_manage_dedicace", as: "creator_manage_dedicace"
    post "projects/creator_chapters_post", to: "projects#creator_chapters_post", as: "creator_chapters_post"
    post "projects/edit_creator_chapters_post", to: "projects#edit_creator_chapters_post",
                                                as: "edit_creator_chapters_post"
    delete "projects/delete_creator_chapter/:id", to: "projects#delete_creator_chapter", as: "delete_creator_chapter"
    post "projects/creator_dedicace_de_fin_post", to: "projects#creator_dedicace_de_fin_post",
                                                  as: "creator_dedicace_de_fin_post"
    post "projects/creator_refresh_video", to: "projects#creator_refresh_video", as: "creator_refresh_video"
    post "projects/approving_collaborator_attachments", to: "projects#approving_collaborator_attachments",
                                                        as: "approving_collaborator_attachments"
    get "projects/invite_collaborators", to: "projects#invite_collaborators", as: "invite_collaborators"
    post "projects/invite_collaborators_post", to: "projects#invite_collaborators_post", as: "invite_collaborators_post"

    delete "projects/delete_collaboration/:id", to: "projects#delete_collaboration", as: "delete_collaboration"
    patch "projects/:id/modify_deadline", to: "projects#modify_deadline", as: "modify_deadline"
    patch "projects/:id/close_project", to: "projects#close_project", as: "close_project"

    get "videos/:id/concat_status", to: "videos#concat_status", as: "video_concat_status"

    # Static pages
    get "about", to: "static#about", as: "about"
    get "pricing", to: "static#pricing", as: "pricing"

    # Users profile pages
    get "profile", to: "users#show", as: :profile

    # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
    # Can be used by load balancers and uptime monitors to verify that the app is live.
    get "up" => "rails/health#show", as: :rails_health_check

    # Defines the root path route ("/")
    root "static#home"
  end
end

app/views/projects/as_collaborator_projects.html.erb
<div class="flex flex-col items-center mb-45">

  <%= render "shared/hello_block"%>

  <%= render "shared/profile_tabs", page_count: 1 %>
</div>
<div class='creator-frame'>

  <%= render "shared/creator_participant_block", creator: false %>

   <div class='mt-8 p-text-16'>
    Ici vous pouvez voir tous les films dans lesquels vous êtes collaborateur.
  </div>
  <hr class='hr-divider-gray mt-8 '/>

  <div class="projects-grid mt-8">
    <% @collaborator_projects.each do |video| %>
      <div class="project-main-block flex flex-col  justify-center items-center">
        <div class="project-block">
          <%if video.paid && video.final_video.attached?%>
            <video controls style="width: 100%; height: 100%; border-radius:12.82px;object-fit: cover;">
              <source src="<%= url_for(video.final_video) %>" type="video/mp4">
            </video>
          <%elsif video.final_video_with_watermark.attached?%>
            <video controls style="width: 100%; height: 100%; border-radius:12.82px;object-fit: cover;">
              <source src="<%= url_for(video.final_video_with_watermark) %>" type="video/mp4">
            </video>
          <%else%>
            <%unless video.preview_id.nil?%>
              <%preview_img = Preview.find(video.preview_id)%>
              <%= image_tag preview_img.image, class: "prev-image preview-prof-img" %>
            <%end%>
          <%end%>
        </div>
        <a href="<%= collaborator_video_details_path(video.id) %>" class="cta-button mt-2" data-turbo="false">Détails du projet</a>
      </div>
    <%end%>
  </div>
</div>

app/views/projects/as_creator_projects.html.erb
<div class="flex flex-col items-center mb-45">

  <%= render "shared/hello_block"%>

  <%= render "shared/profile_tabs", page_count: 1 %>
</div>
<div class="creator-frame">
  <%= render "shared/creator_participant_block", creator: true %>

  <div class='mt-8 p-text-16'>
    Ici, vous pouvez éditer le film, consulter les progrès de tous les participants au film, arrêter la préparation du film ou modifier la date limite pour le film terminé.
  </div>
  <hr class='hr-divider-gray mt-8 mb-8'/>

  <p class="p-text-18-bold mb-4">Films en cours</p>

  <div class="projects-grid">
    <% @creator_projects.each do |video| %>
      <div class="project-main-block flex flex-col justify-center items-center">
        <div class="project-block">
              <div data-controller="dialog" data-action="click->dialog#clickOutside">
                <%= image_tag "icons/Ellipse159.png", alt: "Ellipse Icon", class: "ellipse-prof-video-icon" %>
                <%= image_tag "icons/akar-icons_edit.png", alt: "Edit Icon", class: "edit-prof-video-icon", data: { action: "click->dialog#open" } %>
                <dialog data-dialog-target="modal" class="backdrop:bg-slate-400 backdrop:opacity-80 w-full lg:w-2/3 edit-proj-modal">
                  <div class="w-full h-full flex flex-col justify-start items-center">
                    <div class="flex justify-between items-cente w-80 mt-6">
                      <div class="flex justify-between items-center"><span><%= video&.end_date&.strftime("%d/%m/%Y") %></span></div>
                      <button class="black-link">Partager</button>
                    </div>
                    <% if video.final_video.attached? && video.final_video_with_watermark.attached? %>

                      <div class='flex  flex-row items-center justify-center mt-6'>
                        <video controls style="max-width: 84%; max-height: 460px; border-radius:20px;">
                          <source src="<%= url_for(video.paid ? video.final_video : video.final_video_with_watermark) %>" type="video/mp4">
                        </video>
                      </div>
                    <% else %>
                      <div class="flex relative items-center gap-[61px]">
                        <%= video_tag asset_path('about.mp4'), id: 'about-video-element', controls: false, width: 982, height: 425, poster: asset_path('gemotion-about-video-poster.svg') %>
                        <div id="play-button" class="absolute inset-0 flex items-center justify-center cursor-pointer">
                            <%= image_tag 'icons/about-video-play.svg', alt: 'Play Button' %>
                            <%= image_tag 'icons/video-bottom.png', alt: 'Play Button Icon', class: 'absolute video-bottom-icon' %>
                        </div>
                      </div>
                    <% end %>
                    <div class="flex flex-row justify-between items-center w-80 mt-6">
                      <div class="flex justify-between items-center"><span>Titre</span></div>
                      <input type="text" value="<%= video.title %>" class="w-full px-4 py-2 border rounded-lg bg-gray-100 text-gray-600 disabled-input border-gray-300" disabled>
                    </div>
                    <div class="flex flex-row justify-between items-center w-80 mt-6">
                      <div class="flex justify-between items-center"><span>Description</span></div>
                      <input type="text" value="<%= video.description %>" class="w-full px-4 py-2 border rounded-lg bg-gray-100 text-gray-600 disabled-input border-gray-300" disabled>
                    </div>
                    <div class="flex flex-row justify-end items-center w-80 mt-6">
                      <% if video.final_video.attached? %>
                        <a href="<%= url_for(video.final_video) %>" class="transparent-link" download>
                          Télécharger
                          <%= image_tag "icons/mdi_download-outline.png", alt: "Download Icon", class: "inline-block", style: "height: 16px; width: 16px;" %>
                        </a>
                      <% end %>
                    </div>
                  </div>
                </dialog>
              </div>

          <%if video.paid && video.final_video.attached?%>
            <video controls style="width: 100%; height: 100%; border-radius:12.82px;object-fit: cover;">
              <source src="<%= url_for(video.final_video) %>" type="video/mp4">
            </video>
          <%elsif video.final_video_with_watermark.attached?%>
            <video controls style="width: 100%; height: 100%; border-radius:12.82px;object-fit: cover;">
              <source src="<%= url_for(video.final_video_with_watermark) %>" type="video/mp4">
            </video>
          <%else%>
            <%unless video.preview_id.nil?%>
              <%preview_img = Preview.find(video.preview_id)%>
              <%= image_tag preview_img.image, class: "prev-image preview-prof-img" %>
            <%end%>
          <%end%>
        </div>
        <%= link_to "Voir la progression", participants_progress_path(video_id: video.id), class: "cta-button mt-2", data: {turbo: false} %>
      </div>
    <%end%>
  </div>
</div>

app/views/projects/collaborator_video_details.html.erb
<div class="flex flex-col items-center mb-45">
  <%= render "shared/hello_block"%>
  <%= render "shared/profile_tabs", page_count: 1 %>
</div>

<div class='creator-frame'>

  <%= render "shared/creator_participant_block", creator: false %>

  <div class='mt-4'>
    <div class="project-invitation">
      <div class="flex flex-row items-start mb-2">
        <span class="p-text-16">Ici s'affichent les films auxquels on vous a demandé de participer. Appuyez sur</span>
        <%= image_tag "icons/akar-icons_edit.svg", alt: "Edit Icon", style: "vertical-align: middle; margin-left: 5px; margin-right: 5px;" %>
        <span class="p-text-16">pour :</span>
      </div>

      <ul>
        <li class="p-text-16">Ajouter du contenu vidéo ou photo pour illustrer chaque chapitre.</li>
        <li class="p-text-16">Contribuer à la dédicace finale. S'il s'agit de musique, vous pouvez sélectionner la partie qui leur est accessible.</li>
        <li class="p-text-16">Inviter un ami à collaborer sur le projet (l'administrateur doit approuver le nouveau participant).</li>
      </ul>
    </div>
  </div>

  <div class="w-80 mt-65">
    <h4 class="text-black text-left font-montserrat text-[32px] font-bold leading-[24px] mb-[24px]">Les informations sur le projet en cours</h4>
  </div>
  <div class="flex flex-row items-start mt-4">
    <span class="p-text-16-bold mr-4">Nom du destinataire (pour qui nous préparons le film) :</span>
    <span class="p-text-16"><%= @destinataires&.map(&:name).join(" | ") %></span>
  </div>
  <div class="flex flex-row items-start mt-4">
    <span class="p-text-16-bold mr-4">Occasion :</span>
    <span class="p-text-16"><%= @video&.occasion&.humanize %></span>
  </div>
  <div class="flex flex-row items-start mt-4">
    <span class="p-text-16-bold mr-4">Date de livraison du film :</span>
    <span class="p-text-16"><%=@video&.end_date&.strftime("%d/%m/%Y") %></span>
  </div>

  <hr class='hr-divider-gray mt-65 '/>

  <div class="flex justify-start items-center mt-6">
    <div class="p-text-18-bold">Ajouter mon contenu dans les chapitres</div>
    <a href="<%= collaborator_manage_chapters_path(@video.id) %>" class="transparent-link ml-50" data-turbo="false">Gérer les chapitres</a>
  </div>

  <%if @collaborator_chapters.present? and @collaborator_chapters.count>0%>
    <div class="w-full flex-col justify-center items-center">
      <%= form_with url: edit_collaborator_chapters_post_path(video_id: @video.id), method: :post, html: { class: "flex flex-col justify-center items-center w-full", id: "edit_video_form", data: { turbo: false } } do |f| %>
        <div class="w-100i edit_video_form_block mt-6 flex flex-col justify-center items-center">

          <%= render "videos/shared/popup_edit_video", chapters: @collaborator_chapters, musics: @musics, video: @video, f: f, collab: true %>

          <div class="edit-video-alert w-full">
            <%= image_tag "icons/alert.svg" %>
            <p class="p-text-16">Cliquez et faites glisser pour changer l'ordre</p>
          </div>
          <div class="flex justify-center mt-65">
            <%= f.submit "Confirmer les modifications", class: "black-link" %>
          </div>
        </div>
      <% end %>
    </div>
  <%end%>
  <hr class='hr-divider-gray mt-6'/>

  <div class="flex justify-start items-center mt-6">
    <div class="p-text-18-bold">Participation à la Dédicace de fin</div>
    <%= link_to "Gérer Dédicace de fin", collaborator_manage_dedicace_path(@video.id), data: { turbo: false }, class: "transparent-link ml-50" %>
  </div>
  <%if @collaborator_dedicace.present? && @collaborator_dedicace.creator_end_dedication_video.attached?%>
    <div class="projects-grid mt-8">
      <div class="project-main-block flex flex-col justify-between">
        <div class="project-block">
          <%= video_tag @collaborator_dedicace.creator_end_dedication_video, controls: true, autobuffer: true, class: 'collaborator-dedicace-thumb' %>
        </div>
      </div>
    </div>
  <%end%>
</div>
<script>
document.addEventListener("DOMContentLoaded", () => {
  let currentAudioPlayer = null; // Track the currently playing audio player
  const radioButtons = document.querySelectorAll('input[name="video[music_type]"]');
  const wholeVideoForm = document.getElementById('whole-video-form');
  const byChaptersForm = document.getElementById('by-chapters-form');

  radioButtons.forEach(radio => {
    radio.addEventListener('change', () => {
      // Show or hide forms based on selected radio button
      if (radio.value === 'whole_video') {
        wholeVideoForm.style.display = 'block';
        byChaptersForm.style.display = 'none';
      } else {
        wholeVideoForm.style.display = 'none';
        byChaptersForm.style.display = 'block';
      }
    });
  });

  // Trigger the change event for the currently selected radio button
  const checkedRadio = document.querySelector('input[name="video[music_type]"]:checked');
  if (checkedRadio) {
    checkedRadio.dispatchEvent(new Event('change'));
  }

  document.querySelectorAll(".custom-music-dropdown").forEach((dropdown) => {
    const toggle = dropdown.querySelector(".dropdown-toggle");
    const menu = dropdown.querySelector(".dropdown-menu");
    const hiddenInput = dropdown.nextElementSibling; // Hidden input for the selected music ID

    // Toggle dropdown menu visibility
    // toggle.addEventListener("click", () => {
    //   menu.classList.toggle("visible");
    // });

    // Handle selection of a music option
    menu.querySelectorAll(".dropdown-option input[type='radio']").forEach((radioButton) => {
      const option = radioButton.closest(".dropdown-option");
      const audioSrc = option.querySelector(".custom-audio-player").dataset.audioSrc;

      // Create an audio element dynamically for playback
      let audio = new Audio(audioSrc);

      option.querySelector(".play-button").addEventListener("click", () => {
        // Initialize and resume AudioContext when a user interacts

        // Stop the currently playing audio player, if any
        if (currentAudioPlayer && currentAudioPlayer !== audio) {
          currentAudioPlayer.pause();
          currentAudioPlayer.currentTime = 0; // Reset to the beginning
        }

        // Play the new audio or toggle pause/play for the current one
        if (audio.paused) {
          audio.play();
          currentAudioPlayer = audio; // Update the current audio player
        } else {
          audio.pause();
        }
      });

      radioButton.addEventListener("change", () => {
        const musicId = option.dataset.musicId;
        console.log(musicId)
        console.log(hiddenInput)
        // Update hidden input value
        hiddenInput.value = musicId;
        console.log(hiddenInput.value)
        // Update toggle text
        const musicName = option.querySelector("span").innerText;
        toggle.querySelector("span").innerText = musicName;

        // Close dropdown
        // menu.classList.remove("visible");
      });
    });
  });

  // Close dropdown when clicking outside
  document.addEventListener("click", (event) => {
    document.querySelectorAll(".dropdown-menu.visible").forEach((menu) => {
      if (!menu.parentElement.contains(event.target)) {
        // menu.classList.remove("visible");
      }
    });
  });

  // Stop audio when clicking outside
  document.addEventListener("click", (event) => {
    if (!event.target.closest('.dropdown-menu')) {
      if (currentAudioPlayer) {
        currentAudioPlayer.pause();
        currentAudioPlayer.currentTime = 0; // Reset the current audio
        currentAudioPlayer = null;
      }
    }
  });

  document.addEventListener("click", (event) => {
    const deleteMusicButton = event.target.closest(".delete-music-icon-btn");
    if (deleteMusicButton) {
      const parentBlock = deleteMusicButton.closest(".audio-visualizer");
      const url = deleteMusicButton.dataset.url;

      handleMusicDeletion(url, parentBlock);
    }
  });

  const handleMusicDeletion = async (url, parentBlock) => {
    try {
      if (url) {
        // Handle deletion for existing music files (server-side)
        const response = await fetch(url, {
          method: "DELETE",
          headers: {
            "X-CSRF-Token": document.querySelector('meta[name="csrf-token"]').content,
            Accept: "application/json",
            "Content-Type": "application/json",
          },
        });

        if (!response.ok) {
          console.error(`HTTP error! status: ${response.status}`);
          throw new Error("Server-side deletion failed.");
        }

        const data = await response.json();
        if (data.message) {
          resetMusicBlock(parentBlock);
        } else {
          console.warn("Server did not confirm deletion.");
        }
      } else {
        // Handle deletion for newly added music files
        resetMusicBlock(parentBlock);
      }
    } catch (error) {
      console.error("Error during music deletion:", error);
    } finally {
      // Optional: Reload the page to ensure state is consistent
      location.reload();
    }
  };

  const resetMusicBlock = (parentBlock) => {
    // Remove the block visually
    if (parentBlock) {
      parentBlock.remove();
    }
  };

});
</script>
<style>
.delete-music-icon-btn{
  position: absolute;
  width: 40px;
  height: 40px;
  top: 0;
  right: 0;
}
.purge-music-icon{
  position: absolute !important;
  top: 10px !important;
  right: 10px !important;
  width: 40px !important;
  height: 40px !important;
  z-index: 2 !important;
  display: block !important;
}
.audio-visualizer {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 10px 20px;
  border-radius: 30px; /* Rounded container */
  background: rgba(242, 252, 255, 1); /* Light blue */
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.waveform-canvas {
  width: 100%;
  height: 32px;
  overflow: hidden;
}
.custom-music-dropdown {
  position: relative;
  width: 100%;
  height: 57px;
  padding: 16px 40px 16px 20px;
  border-radius: 8px;
  background: var(--Blue, rgba(242, 252, 255, 1));
  appearance: none;
  -webkit-appearance: none;
  font-family: 'Red Hat Display', sans-serif;
  font-size: 16px;
  font-weight: 400;
  line-height: 25px;
  text-align: left;
  background-clip: padding-box;
  z-index: 1;
}

.custom-music-dropdown::before {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  border-radius: 8px;
  padding: 1px; /* Border thickness */
  background: linear-gradient(
    205.68deg,
    rgba(201, 225, 255, 0.2) 19.49%,
    rgba(13, 103, 131, 0.2) 60.63%,
    rgba(22, 63, 80, 0.2) 90.92%
  );
  -webkit-mask: linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0);
  mask: linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0);
  -webkit-mask-composite: destination-out;
  mask-composite: exclude;
  z-index: -1; /* Place below the dropdown content */
}
.music-dropdown-radio{
  margin-top: 20px;
}
.dropdown-toggle {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 10px;
  font-size: 16px;
  border-radius: 8px;
}

.dropdown-arrow {
  margin-left: 10px;
}

.dropdown-menu {
  position: absolute;
  top: 100%;
  left: 0;
  width: 100%;
  background: #fff;
  border: 1px solid #ccc;
  border-radius: 8px;
  box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
  max-height: 215px;
  overflow-y: auto;
  z-index: 1000;
  display: none;
}

.dropdown-menu.visible {
  display: block;
}

.dropdown-option {
  display: flex;
  align-items: center;
  padding: 10px 25px;
  cursor: pointer;
  border-bottom: 1px solid #eee;
}

.dropdown-option:last-child {
  border-bottom: none;
}

.dropdown-option:hover {
  background: rgba(201, 225, 255, 0.5);
}
.edit-music-video-icon{
  width: 24px !important;
  height: 24px  !important;
  border: none !important;
  margin-left: 15px !important;
}
</style>

app/views/projects/invite_collaborators.html.erb
<div>

  <%if @video.colab?%>
    <h1 class="video-h1">Invitez vos proches à participer  à votre projet</h1>
  <%else%>
    <h1 class="video-h1">Invitez des amis à collaborer sur  votre projet !</h1>
  <%end%>

  <div class="flex flex-row justify-center w-full">
    <%= image_tag 'left-no-star.png', class: 'image-sides left-image' %>
    <div class="content w-full flex flex-col justify-center items-center">

      <div class="">

        <div class="frame">

          <h4 class="video-h4">Envoyez une invitation via un lien  whatsapp, facebook, instagram ou en envoyant un email</h4>

          <%= form_with url: invite_collaborators_post_path(video_id: @video.id), method: :post do |f| %>
            <div class="share-wrapper">
              <%= f.email_field :email, placeholder: "Email", class:"share-email" %>
              <%= f.submit "Inviter", class:"share-submit" %>
            </div>
          <% end %>

          <p class="p-text-16">Ou partagez le lien</p>

          <div class="share-clipboard" data-controller="clipboard">
            <div class="share-clipboard-wrapper">
              <%= image_tag "icons/tabler_link.png" %>
              <span><%= join_url(@video.token) %></span>
            </div>
            <span data-action="click->clipboard#copy" data-clipboard-value-param="<%= join_url(@video.token) %>" class="share-clipboard-btn">Copier</span>
          </div>

          <div class="flex flex-row justify-center items-center">
            <%= image_tag "icons/whats-share.png", class: 'share-icon-whats'%>
            <%= image_tag "icons/facebook-share.png", class: 'share-icon-facebook' %>
          </div>
        </div>

        <div class="flex flex-row justify-center items-center mt-35">
          <%= link_to "Retour à la page précédente", participants_progress_path(video_id: @video.id), class: "black-link", data: {turbo: false} %>
        </div>
      </div>
    </div>
    <%= image_tag 'right-with-star.png', class: 'image-sides right-image' %>
  </div>
</div>