config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  scope "(:locale)", locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users
    resources :users, only: %i[show edit update] # Add other actions if needed

    post "flush_and_reseed", to: "static#flush_and_reseed"
    # resources :contacts, only: [:new, :create]

    resources :contacts, only: %i[new create]

    # Video
    get "videos/back", to: "videos#go_back", as: "step_back"
    get "videos/go_to_select_chapters", to: "videos#go_to_select_chapters", as: "go_to_select_chapters"

    get "videos/start", to: "videos#start", as: "start"
    post "videos/start", to: "videos#start_post", as: "start_post"

    get "videos/occasion", to: "videos#occasion", as: "occasion"
    post "videos/occasion", to: "videos#occasion_post", as: "occasion_post"

    # get 'videos/destinataire', to: "videos#destinataire", as: "destinataire"
    # post 'videos/destinataire', to: "videos#destinataire_post", as: "destinataire_post"

    get "videos/info_destinataire", to: "videos#info_destinataire", as: "info_destinataire"
    post "videos/info_destinataire", to: "videos#info_destinataire_post", as: "info_destinataire_post"

    get "videos/destinataire_details", to: "videos#destinataire_details", as: "destinataire_details"
    post "videos/destinataire_details_post", to: "videos#destinataire_details_post", as: "destinataire_details_post"
    delete "videos/delete_destinataire/:id", to: "videos#delete_destinataire", as: "delete_destinataire"
    patch "videos/update_destinataire/:id", to: "videos#update_destinataire", as: "update_destinataire"

    get "videos/date_fin", to: "videos#date_fin", as: "date_fin"
    post "videos/date_fin", to: "videos#date_fin_post", as: "date_fin_post"

    get "videos/introduction", to: "videos#introduction", as: "introduction"
    post "videos/introduction", to: "videos#introduction_post", as: "introduction_post"

    get "videos/photo_intro", to: "videos#photo_intro", as: "photo_intro"
    post "videos/photo_intro", to: "videos#photo_intro_post", as: "photo_intro_post"
    delete "videos/drop_preview/:id", to: "videos#drop_preview", as: "drop_preview"

    get "videos/select_chapters", to: "videos#select_chapters", as: "select_chapters"
    post "videos/select_chapters", to: "videos#select_chapters_post", as: "select_chapters_post"

    get "videos/music", to: "videos#music", as: "music"
    post "videos/music", to: "videos#music_post", as: "music_post"
    patch "videos/update_video_music_type", to: "videos#update_video_music_type", as: "update_video_music_type"
    delete "videos/drop_custom_music/:id", to: "videos#drop_custom_music", as: "drop_custom_music"

    get "videos/dedicace", to: "videos#dedicace", as: "dedicace"
    post "videos/dedicace", to: "videos#dedicace_post", as: "dedicace_post"

    get "videos/share", to: "videos#share", as: "share"
    post "videos/share", to: "videos#share_post", as: "share_post"
    get "videos/skip_share", to: "videos#skip_share", as: "skip_share"

    get "videos/content", to: "videos#content", as: "content"
    post "videos/content", to: "videos#content_post", as: "content_post"
    get "videos/skip_content", to: "videos#skip_content", as: "skip_content"

    get "videos/content_dedicace", to: "videos#content_dedicace", as: "content_dedicace"
    get "videos/:id/stream", to: "videos#stream_video", as: "stream_video"
    post "videos/content_dedicace", to: "videos#content_dedicace_post", as: "content_dedicace_post"
    get "videos/skip_content_dedicace", to: "videos#skip_content_dedicace", as: "skip_content_dedicace"

    get "videos/deadline", to: "videos#deadline", as: "deadline"
    post "videos/deadline", to: "videos#deadline_post", as: "deadline_post"
    get "videos/skip_deadline", to: "videos#skip_deadline", as: "skip_deadline"

    get "videos/dedicace_de_fin", to: "videos#dedicace_de_fin", as: "dedicace_de_fin"
    patch "/:id/videos/dedicace_de_fin_post", to: "videos#dedicace_de_fin_post", as: "dedicace_de_fin_post"
    get "videos/skip_dedicace_de_fin", to: "videos#skip_dedicace_de_fin", as: "skip_dedicace_de_fin"

    get "videos/confirmation", to: "videos#confirmation", as: "confirmation"
    post "videos/confirmation", to: "videos#confirmation_post", as: "confirmation_post"
    get "videos/skip_confirmation", to: "videos#skip_confirmation", as: "skip_confirmation"

    patch "videos/:id/update_video_slot", to: "videos#update_video_slot", as: "update_video_slot"

    get "videos/:id/get_video_slot_status", to: "videos#get_video_slot_status", as: "get_video_slot_status"

    get "videos/edit_video", to: "videos#edit_video", as: "edit_video"
    post "videos/edit_video_post", to: "videos#edit_video_post", as: "edit_video_post"
    get "videos/skip_edit_video", to: "videos#skip_edit_video", as: "skip_edit_video"
    delete "videos/delete_video_chapter/:id", to: "videos#delete_video_chapter", as: "delete_video_chapter"
    delete "videos/purge_chapter_attachment/:id", to: "videos#purge_chapter_attachment", as: "purge_chapter_attachment"

    get "videos/payment", to: "videos#payment", as: "payment"
    post "videos/payment_post", to: "videos#payment_post", as: "payment_post"

    get "videos/render_final_page", to: "videos#render_final_page", as: "render_final_page"

    get "join/videos/:id", to: "videos#join", as: "join"

    get "projects/as_creator", to: "projects#as_creator_projects", as: "as_creator_projects"
    get "projects/as_collaborator", to: "projects#as_collaborator_projects", as: "as_collaborator_projects"
    get "projects/participants_progress", to: "projects#participants_progress", as: "participants_progress"
    get "projects/collaborator_video_details/:id", to: "projects#collaborator_video_details",
                                                   as: "collaborator_video_details"

    get "projects/collaborator_manage_chapters/:id", to: "projects#collaborator_manage_chapters",
                                                     as: "collaborator_manage_chapters"
    get "projects/collaborator_manage_dedicace/:id", to: "projects#collaborator_manage_dedicace",
                                                     as: "collaborator_manage_dedicace"
    post "projects/collaborator_chapters_post", to: "projects#collaborator_chapters_post",
                                                as: "collaborator_chapters_post"
    post "projects/edit_collaborator_chapters_post", to: "projects#edit_collaborator_chapters_post",
                                                     as: "edit_collaborator_chapters_post"
    delete "projects/delete_collaborator_chapter/:id", to: "projects#delete_collaborator_chapter",
                                                       as: "delete_collaborator_chapter"
    post "projects/collaborator_dedicace_de_fin_post", to: "projects#collaborator_dedicace_de_fin_post",
                                                       as: "collaborator_dedicace_de_fin_post"

    get "projects/creator_manage_chapters/:id", to: "projects#creator_manage_chapters", as: "creator_manage_chapters"
    get "projects/creator_manage_dedicace/:id", to: "projects#creator_manage_dedicace", as: "creator_manage_dedicace"
    post "projects/creator_chapters_post", to: "projects#creator_chapters_post", as: "creator_chapters_post"
    post "projects/edit_creator_chapters_post", to: "projects#edit_creator_chapters_post",
                                                as: "edit_creator_chapters_post"
    delete "projects/delete_creator_chapter/:id", to: "projects#delete_creator_chapter", as: "delete_creator_chapter"
    post "projects/creator_dedicace_de_fin_post", to: "projects#creator_dedicace_de_fin_post",
                                                  as: "creator_dedicace_de_fin_post"
    post "projects/creator_refresh_video", to: "projects#creator_refresh_video", as: "creator_refresh_video"
    post "projects/approving_collaborator_attachments", to: "projects#approving_collaborator_attachments",
                                                        as: "approving_collaborator_attachments"
    get "projects/invite_collaborators", to: "projects#invite_collaborators", as: "invite_collaborators"
    post "projects/invite_collaborators_post", to: "projects#invite_collaborators_post", as: "invite_collaborators_post"

    delete "projects/delete_collaboration/:id", to: "projects#delete_collaboration", as: "delete_collaboration"
    patch "projects/:id/modify_deadline", to: "projects#modify_deadline", as: "modify_deadline"
    patch "projects/:id/close_project", to: "projects#close_project", as: "close_project"

    get "videos/:id/concat_status", to: "videos#concat_status", as: "video_concat_status"

    # Static pages
    get "about", to: "static#about", as: "about"
    get "pricing", to: "static#pricing", as: "pricing"

    # Users profile pages
    get "profile", to: "users#show", as: :profile

    # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
    # Can be used by load balancers and uptime monitors to verify that the app is live.
    get "up" => "rails/health#show", as: :rails_health_check

    # Defines the root path route ("/")
    root "static#home"
  end
end

app/models/video.rb
class Video < ApplicationRecord
  enum :video_type, { solo: 0, colab: 1 }
  enum :occasion, { anniversaire: 0, mariage: 1 }
  enum :theme, { specific_request: 0, theme_1: 1, theme_2: 2 }
  enum :introduction_video, {notre_star_ce_soir: 0}
  enum :music_type, { whole_video: 0, by_chapters: 1 }
  enum concat_status: { pending: 0, processing: 1, completed: 2, failed: 3 }
  enum project_status: { started: 0, in_progress: 1, finished: 2, closed: 3 }

  has_many :video_destinataires, dependent: :destroy
  has_many :video_chapters, dependent: :destroy
  has_many :dedicace_contents, dependent: :destroy
  has_many :collaborations, dependent: :destroy
  has_many :collaborator_dedicaces, dependent: :destroy
  has_many :collaborator_chapters, dependent: :destroy
  has_one :video_dedicace, dependent: :destroy

  # has_many :video_musics, dependent: :destroy
  # has_many :musics, through: :video_musics

  has_many :video_previews, dependent: :destroy
  has_many :previews, through: :video_previews
  has_many :collaborations, dependent: :destroy

  has_one_attached :final_video
  has_one_attached :final_video_with_watermark
  has_one_attached :final_video_with_transition
  has_one_attached :final_video_xml

  belongs_to :user
  belongs_to :music, optional: true
  belongs_to :dedicace, optional: true

  SOLO_WAY = %w[start occasion info_destinataire destinataire_details date_fin introduction
                photo_intro select_chapters music dedicace share content deadline edit_video content_dedicace payment]
  COLAB_WAY = %w[start occasion info_destinataire destinataire_details date_fin introduction
                 photo_intro select_chapters music dedicace share content dedicace_de_fin confirmation deadline edit_video content_dedicace payment]

  def video_destinataire
    video_destinataires.last
  end

  def final_video_duration
    if final_video.attached? && final_video.blob.present?
      analyzer = ActiveStorage::Analyzer::VideoAnalyzer.new(final_video.blob)
      metadata = analyzer.metadata
      metadata[:duration] if metadata
    else
      nil
    end
  end

  def get_preview
    return unless video.previewable? # => true

    img_preview = video.preview(resize: "800x1400").processed # Returns an active storage instance with the file type mp4 instead of the expected png thumbnail
    img_preview.service_url # Fails with exception (see next snippet)
  end

  def generate_token
    self.token = SecureRandom.urlsafe_base64(20)
    generate_token if Video.exists?(token:)
  end

  def validate_start
    Video.video_types.keys.include?(video_type.downcase) && way.include?(stop_at)
  end

  def validate_occasion
    Video.occasions.keys.include?(occasion.downcase) && way.include?(stop_at)
  end

  def validate_destinataire(video_destinataire)
    VideoDestinataire.genres.keys.include?(video_destinataire.genre) && way.include?(stop_at)
  end

  def validate_info_destinataire(video_destinataire)
    return false if video_destinataire.name.empty?
    return false if video_destinataire.age.nil? || !video_destinataire.age.is_a?(Numeric)
    # return false if video_destinataire.more_info.empty?
    return false if video_destinataire.passions_and_hobbies.empty?
    return false if video_destinataire.personality_description.empty?
    return false if video_destinataire.favorite_quotes.empty?
    return false unless way.include?(stop_at)

    true
  end

  def validate_date_fin
    return false if end_date.nil? || !end_date.is_a?(ActiveSupport::TimeWithZone)
    return false unless way.include?(stop_at)

    true
  end

  def validate_introduction
    return false unless Video.introduction_videos.include?(introduction_video.downcase)
    return false if specific_request? && theme_specific_request.blank?
    return false unless way.include?(stop_at)

    true
  end

  def validate_photo_intro
    return false if previews.count > 3 || previews.count == 0

    true
  end

  def next_step
    curr_step = way.find_index stop_at
    return 0 if curr_step.nil?
    return way.size if finish?

    way[curr_step + 1]
  end

  def finish?
    current_step == way.last
  end

  def current_step
    curr_step = way.find_index stop_at
    return way[0] if curr_step.nil?

    way[curr_step]
  end

  def previous_step
    curr_step = way.find_index stop_at
    return way[0] if curr_step.nil? || curr_step <= 0

    way[curr_step - 1]
  end

  def way
    return SOLO_WAY if video_type == "solo"

    COLAB_WAY
  end

  def self.calculate_duration(duration_in_seconds)
    (duration_in_seconds.to_f / 60).ceil
  end

  def self.calculate_price(duration_in_minutes)
    p "*" * 100
    p duration_in_minutes
    p "*" * 100
    if duration_in_minutes > 0 && duration_in_minutes <= 5
      duration_in_minutes * 20
    elsif duration_in_minutes > 5 && duration_in_minutes <= 15
      duration_in_minutes * 15
    elsif duration_in_minutes > 15
      duration_in_minutes * 10
    else
      0
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/shared/_back_button.html.erb
<%= link_to t("previous_step"), step_back_path, class: "black-link", data: {turbo: false} %>

app/views/videos/shared/_popup_edit_video.html.erb
<div id="chapters-list" class="chapters-grid mt-8" data-controller="chapter-management" data-chapter-management-target="chaptersList">
  <% chapters.each do |chapter| %>
    <div class="project-main-block flex flex-col justify-between items-center chapter-item" data-id="<%= chapter.id %>">
      <div class="project-block">

        <div class="delete-chap-icon-btn" data-url="<%= delete_video_chapter_path(chapter.id) %>" data-confirm="Are you sure you want to delete this chapter?" data-action="click->chapter-management#deleteChapter">
          <%= image_tag "icons/delete-icon.png", alt: "Delete Icon", class: "delete-chap-icon" %>
        </div>
        <div class="project-block-bottom-white">
          <div class="text-left-important p-text-18"><%= chapter.chapter_type.name %></div>
          <div class="p-text-16"><%= chapter.text %></div>
        </div>
        <div data-controller="dialog" data-action="click->dialog#clickOutside">
          <%= image_tag "icons/tdesign_more_white.png", alt: "Edit Icon", class: "edit-video-icon", data: { action: "click->dialog#open" } %>
          <dialog data-dialog-target="modal" class="backdrop:bg-slate-400 backdrop:opacity-80 w-full lg:w-2/3 edit-chap-modal">
            <div class="w-full h-full flex flex-col justify-start items-center">
              <h3 class="video-h3 tt-uppercase mt-8">Modifier un chapitre</h3>
              <div class="video-memory-edit-video mb-8">
                <div class="video-memory-thumb-wrapper">
                  <% if chapter.chapter_type.image.attached? %>
                    <%= image_tag chapter.chapter_type.image, class: "h-[150px] w-[200px] object-cover rounded" %>
                  <% else %>
                    <p>Pas d'image</p>
                  <% end %>
                </div>
                <div class="w-full video-popup-input-block">
                  <%= f.text_field "chapters[#{chapter.id}][text]", value: chapter.text, placeholder: "Quel texte doit contenir ce chapitre ...", class: "w-full br-10" %>
                </div>
                <div id="edit-video-gallery-<%= chapter.id %>" class="edit-video-gallery flex flex-row items-center space-x-8">
                  <% chapter.ordered_videos.each do |video| %>
                    <div class="edit-video-container old-video-container" data-file-name="<%= video.filename.to_s %>">
                      <%= video_tag video, controls: true, autobuffer: true %>
                      <div class="purge-attachment-icon-btn" data-url="<%= purge_chapter_attachment_path(video.id) %>" data-action="click->chapter-management#deleteAttachment">
                        <%= image_tag "icons/delete-icon.png", alt: "Delete Icon", class: "purge-chap-icon" %>
                      </div>
                    </div>
                  <% end %>
                </div>
                <%= f.hidden_field "chapters[#{chapter.id}][videos_order]", id: "videos_order_#{chapter.id}" %>

                <div class="upload-attachment-block flex flex-col justify-center items-center">
                  <span class="text-center">Faites glisser ou appuyez pour ajouter vos vidéos</span>
                  <div class="add-more-circle mt-6" data-chapter-management-target="customUploadButtonVideos" data-action="click->chapter-management#triggerVideoUpload" data-id="<%= chapter.id %>">
                    <span class="plus-sign">+</span>
                  </div>
                  <%= f.file_field "chapters[#{chapter.id}][videos]", multiple: true, accept: 'video/*', class: 'form-control', style: 'display: none;', "data-id": chapter.id, "data-action": "change->chapter-management#handleVideoChange" %>
                </div>
                <hr class="hr-divider-gray mt-4 mb-4"/>
                <div id="edit-photo-gallery-<%= chapter.id %>" class="edit-video-gallery flex flex-row items-center space-x-8">
                  <% chapter.ordered_photos.each do |photo| %>
                    <div class="edit-image-container old-image-container" data-file-name="<%= photo.filename.to_s %>">
                      <%= image_tag photo.variant(resize_to_fill: [200, 200]).processed, class: "prev-image" %>
                      <div class="purge-attachment-icon-btn" data-url="<%= purge_chapter_attachment_path(photo.id) %>" data-action="click->chapter-management#deleteAttachment">
                        <%= image_tag "icons/delete-icon.png", alt: "Delete Icon", class: "purge-chap-icon" %>
                      </div>
                    </div>
                  <% end %>
                </div>
                <%= f.hidden_field "chapters[#{chapter.id}][photos_order]", id: "images_order_#{chapter.id}" %>

                <div class="upload-attachment-block flex flex-col justify-center items-center">
                  <span class="text-center">Faites glisser ou appuyez pour ajouter vos photos</span>
                  <div class="add-more-circle mt-6" data-chapter-management-target="customUploadButtonPhotos" data-action="click->chapter-management#triggerPhotoUpload" data-id="<%= chapter.id %>">
                    <span class="plus-sign">+</span>
                  </div>
                  <%= f.file_field "chapters[#{chapter.id}][photos]", multiple: true, accept: 'image/*', class: 'form-control', style: 'display: none;', "data-id": chapter.id, "data-action": "change->chapter-management#handlePhotoChange" %>
                </div>
                <hr class="hr-divider-gray mt-4 mb-4"/>
                <% if video.by_chapters? %>
                  <div class="music-selection w-full">
                    <%if chapter.custom_music.attached? && chapter.waveform.present?%>
                      <div class="relative audio-visualizer custom-audio-player" data-controller="audio-visualizer" data-audio-src="<%= url_for(chapter.custom_music) %>" data-waveform="<%= chapter.waveform.to_json %>">
                        <div class="play-icon play-button" data-audio-visualizer-target="playPauseButton">
                          <div class="play-button-icon"></div>
                        </div>
                        <canvas class="waveform-canvas" data-audio-visualizer-target="waveformCanvas"></canvas>
                      </div>
                    <%end%>
                    <div class="w-100i text-center h-170i upload-music-block flex flex-col justify-center items-center">
                      <label for="custom_music_<%= chapter.id %>" class="cursor-pointer flex flex-col justify-center items-center w-full">
                        <span>Ajoutez votre piste de musique (lien youtube, mp3)</span>
                        <div class="add-more-circle mt-6">
                          <span class="plus-sign">+</span>
                        </div>
                      </label>
                      <input type="file"
                            id="custom_music_<%= chapter.id %>"
                            name="custom_music_<%= chapter.id %>"
                            class="hidden custom-music-file-input"
                            accept="audio/mpeg">
                    </div>



                    <div class="w-full flex justify-center items-center p-text-center-bold-16">ou</div>
                    <div class="w-full">
                      <%if collab%>
                        <% selected_music_id = chapter.collaborator_music&.music_id %>
                      <%else%>
                        <% selected_music_id = chapter.video_music&.music_id %>
                      <%end%>
                      <div class="custom-music-dropdown flex justify-between items-center" data-selected-music="<%= selected_music_id %>">
                        <div class="dropdown-toggle w-100i">
                          <% if selected_music_id.present? %>
                            <%if collab%>
                              <span><%= chapter.collaborator_music&.music&.name %></span>
                            <%else%>
                              <span><%= chapter.video_music&.music&.name %></span>
                            <%end%>
                          <% else %>
                            <span>Choisissez la musique dans la liste ci-dessous</span>
                          <% end %>
                          <div class="dropdown-arrow">&#9662;</div>
                        </div>
                        <div class="dropdown-menu visible mt-2">
                          <% musics.each do |music| %>
                            <label class="dropdown-option flex justify-center items-center" data-music-id="<%= music[:id] %>">
                              <div class="flex flex-col">
                                <span class="p-text-16"><%= music[:name] %></span>
                                <div class="flex flex-row justify-start items-center">
                                  <input type="radio" class="mr-6" name="music_<%= chapter.id %>" value="<%= music[:id] %>" <%= selected_music_id == music[:id] ? 'checked' : '' %> />
                                  <div class="flex flex-col w-full">
                                    <div class="audio-visualizer custom-audio-player" data-controller="audio-visualizer" data-audio-src="<%= music[:url] %>" data-waveform="<%= music[:waveform] %>">
                                      <div class="play-icon play-button" data-audio-visualizer-target="playPauseButton">
                                        <div class="play-button-icon"></div>
                                      </div>
                                      <canvas class="waveform-canvas" data-audio-visualizer-target="waveformCanvas"></canvas>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </label>
                          <% end %>
                        </div>
                      </div>
                      <%= f.hidden_field "music_#{chapter.id}", value: selected_music_id, class: "selected-music-id" %>
                    </div>
                  </div>
                <% end %>

              </div>
              <%= button_tag type: 'button', formmethod: 'dialog', class: 'black-link mb-15', data: { action: 'click->dialog#close' } do %>
                Sauvegarder les modification
              <% end %>
            </div>
          </dialog>
        </div>
        <% if chapter.chapter_type.image.attached? %>
          <%= image_tag chapter.chapter_type.image, class: "preview-prof-img" %>
        <% end %>
      </div>
    </div>
  <% end %>
  <input type="hidden" name="chapter_order" id="chapter_order" />
</div>

app/views/videos/shared/_select_chapters_modal.html.erb
<dialog data-dialog-target="modal" class="backdrop:bg-slate-400 backdrop:opacity-80 w-full lg:w-2/3 popup-chap-modal">
    <h3 class="video-h3 mt-6 mb-[32px] tt-uppercase"><%= t('videos.shared.select_chapters_modal.customize_film') %></h3>
    <div class="w-full flex-im flex-row justify-center items-start">
        <div class="chapter-popup-block">
        <div class="video-chapter-thumb-wrapper">
            <div class="video-chapter-thumb-wrapper-simpletext">
            <% if res[:ct].image.attached? %>
                <%= image_tag res[:ct].image, class: "video-chapter-thumb" %>
            <% else %>
                <p><%= t('videos.shared.select_chapters_modal.no_image') %></p>
            <% end %>
            <div class="flex flex-row justify-start items-center video-chapter-thumb-wrapper-text">
                <%= res[:ct].name %>
                <%= image_tag "icons/carbon_edit.png", class: "ml-15"%>
            </div>
            </div>
            <p class="mt-2 mb-2 p-text-16">"<%= t('videos.shared.select_chapters_modal.chapter_description') %>"</p>
            <div class="font-bold"><%= t('videos.shared.select_chapters_modal.choose_slide_color') %></div>
            <div class="color-picker flex-im flex-row justify-start items-center mt-4">
            <% colors = { white: 'white', red: 'red', orange: 'orange', yellow: 'yellow', green: 'green', lightblue: 'lightblue', dodgerblue: 'dodgerblue', violet: 'violet' } %>
            <% default_color = colors.keys.first.to_s %> <!-- Set the default color to the first in the list -->
            <% colors.each do |color_name, color_value| %>
                <%= f.radio_button "chapters[#{res[:ct].id}][slide_color]", color_value,
                                id: "#{color_value}_#{res[:ct].id}",
                                checked: (res[:slide_color] == color_value || (res[:slide_color].nil? && color_value == default_color)) %>
                <%= f.label "#{color_value}_#{res[:ct].id}", "&nbsp;".html_safe, class: "color-circle #{color_value}" %>
            <% end %>
            </div>
            <div class="font-bold mt-4"><%= t('text') %></div>
            <div class="text-options">
            <div class="form-group">
                <%= f.select "chapters[#{res[:ct].id}][text_family]", options_for_select(['Poppins','Arial', 'Helvetica', 'Times New Roman', 'Verdana', 'Courier New'], res[:text_family]), {}, class: 'custom-select w-full mt-2' %>
            </div>

            <div class="form-group">
                <%= f.select "chapters[#{res[:ct].id}][text_style]", options_for_select(['Normal', 'Bold', 'Italic', 'Bold Italic'], res[:text_style]), {}, class: 'custom-select w-full mt-2' %>
            </div>

            <div class="form-group">
                <%= f.select "chapters[#{res[:ct].id}][text_size]", options_for_select([12, 14, 16, 18, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56], res[:text_size]), {}, class: 'custom-select w-full mt-2' %>
            </div>
            </div>

            <div class="prev-your-text flex-im justify-start items-center"><%= t('videos.shared.select_chapters_modal.preview_text') %></div>
            <%= button_tag type: 'button', formmethod: 'dialog', class: 'black-link w-100i', data: { action: 'click->dialog#close' } do %>
            <%= t('apply_changes') %>
            <%= image_tag 'icons/mdi_magic.png', alt: 'Download Icon', class: 'inline-block', style: 'height: 16px; width: 16px; margin-left: 10px; margin-bottom:3px;' %>
            <% end %>
        </div>
        </div>
    </div>
</dialog>

app/views/videos/shared/_transition_modal.html.erb
<div id="transition-modal" class="fixed inset-0 bg-black bg-opacity-50 hidden flex items-center justify-center z-50">
  <div class="bg-white p-8 rounded-lg w-11/12 md:w-2/3 lg:w-1/2 max-h-90vh overflow-y-auto">
    <h2 class="text-2xl font-bold mb-4"><%= t("add_transition_to_image") %></h2>

    
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
      <div>
        <label for="transition-type" class="block mb-2 font-bold"><%= t("transition") %></label>
        <select id="transition-type" class="w-full p-2 border rounded">
          <option value="dissolve" selected><%= t("dissolve") %></option>
          <option value="flash"><%= t("flash_transition") %></option>
          <option value="directional"><%= t("directional") %></option>
          <option value="zoom"><%= t("zoom") %></option>
          <option value="radial"><%= t("radial") %></option>
          <option value="centered_drop"><%= t("centered_drop") %></option>
          <option value="cube"><%= t("cube") %></option>
          <option value="heart"><%= t("heart") %></option>
        </select>
      </div>
    </div>
    
    <input type="hidden" id="current-preview-id">
    <input type="hidden" id="current-preview-position">
    
    <div class="flex justify-end gap-4">
      <button id="cancel-transition" class="px-4 py-2 bg-gray-300 rounded"><%= t("cancel") %></button>
      <button id="save-transition" class="px-4 py-2 bg-blue-600 rounded"><%= t("save") %></button>
    </div>
  </div>
</div>